routergroup.go

Minus the small reformat that Goimports automatically made with the structure of imports, this just adds a few helper methods to the Router Group that would help us as we are using them in our project.
If you want, I can remove the import reordering.
Thanks for Gin!

Adding helper functions to router group for LINK and UNLINK.

---

Godeps/Godeps.json
README.md

In current gin version, if we use demo like this
```go
func main() {
// If no other routers match /user/john, it will redirect to /user/join/
r.GET("/user/:name/*action", func(c *gin.Context) {
name := c.Params.ByName("name")
action := c.Params.ByName("action")
message := name + " is " + action
c.String(200, message)
})
// Listen and server on 0.0.0.0:8080
r.Run(":8080")
}
```
It cannot handle request **/user/john**, but it could handle **/user/john/**, and the demo is extrally copied from the readme, the  actually reason that why the demo in readme can handle **/user/john**  is that it's handled by
```go
r.GET("/user/:name", func(c *gin.Context) {
name := c.Params.ByName("name")
message := "Hello "+name
c.String(200, message)
})
```
not the
```go …
```

Fix named parameter handle bugs

---

context_test.go
render/render.go

Content type charset is not specified for renderers, currently there's no way to configure it. I believe this might be a sane default.

Specify utf-8 as content type charset on renderers

---

README.md

Fixing typo in Form parameters example

---

auth.go
auth_test.go

Depending on the use case, it might be useful to be able to have different realms for different route groups.

Add customizable Realm for Basic authentication

---

binding/binding.go

This fix can help validating sub structures, for example we have something like this:
```go
struct {
RequiredField int `json:"required"`
OptionalField struct{
RequiredSubField string `json:"optional_sub_field" binding:"required"` 
OptionalSubField string `json:"optional_sub_field"`
}  `json:"optional_field"`
}
```
Without this patch Bind wont fail on something like this json
```go
{
"optional_field": {
"optional_sub_field": "more"
},
"required_field": 10
}
```
This allow to define optional fields, that, if present, shoud fit some critreias.

Add validating sub structures

---

Godeps/Godeps.json
gin.go

Include NoMethod method to Gin to allow middleware handling of 405 errors. Use just as you use the NoRoute method which gin already bundles so for example:
```go
r := gin.Default() //start gin with default middlewares
r.Use(gzip.Gzip(gzip.DefaultCompression))  //add the gzip middleware to normal routes
r.NoRoute(gzip.Gzip(gzip.DefaultCompression)) //pass 404 errors to gzip middleware
r.NoMethod(gzip.Gzip(gzip.DefaultCompression)) //pass 405 No Method errors to gzip middleware
```
without the `r.NoMethod(...)` call, 405 No Method errors are not handled by any gin middleware and simply fall through to the go http.Router

Include NoMethod method to Gin to allow middleware handling of 405 errors

---

routergroup.go

Minor bug where the absolute path would get duplicated for static rendering. HEAD and GET expect relative paths, and convert those to absolute paths. Static was passing them absolute paths causing duplicated pathing
```
/doc/doc/*filepath
```
instead of
```
/doc/*filepath
```
Fixed with @arnoldcano

Fixing bug with static pathing

---

binding/binding.go

We had the following issue:
```
type Event struct {
Timestamp string `form:"timestamp" json:"timestamp,omitempty"`
}
type AnotherEvent struct {
Event
Value string `form:"value" json:"value,omitempty"`
}
```
Using gins default Bind the embedded struct is ignored. This pull request adds support for embedded structs. Not sure if this is useful in general.

add support for embedded struct to Bind

---

examples/realtime-advanced/stats.go

This causes a compile bug preventing godeps :(,  go version <1.4 I think (1.3.3)

Fixing compile bug

---

gin.go
routergroup.go
routergroup_test.go

I like working with modules, with [routesInterface](https://github.com/gin-gonic/gin/blob/master/routergroup.go#L14) exported we can construct function that set routes for a give group or directly for the engine

Exporting routesInterface

---

context.go
context_test.go

According to the documentation IsAborted() method should return true if the current context was aborted. 
At the moment it  works only for the Handlers in which Abort() method was triggered. It doesn't work in the previous Handlers after the c.Next() call. It is because c.index will be higher then AbortIndex.
In my applications I would like to be able to determine whether the Context was aborted after the request was processed, without having to populate c.Errors slice.

Fix IsAborted() method

---

gin.go

Which is not likely the desired behavior.
RedirectTrailingSlash setting is meant to cause a redirect, but the code is never called because the setting wasn't being checked. Instead RedirectFixedPath was being checked.

RedirectTrailingSlash has no effect unless RedirectFixedPath is set

---

context.go

I took a stab at clarifying the `context.Abort` func. Seems there's some confusion for us newbies as to how it's supposed to be used.

Clarify context.Abort docs

---

debug.go
debug_test.go

'DELETE' is 6 chars and breaks indent of the routes dump (only 5 chars were reserved for the HTTP method).

Fix indent of routes debug prints

---

context_test.go
debug_test.go
gin_test.go
utils_test.go

The path of a package can change in a situation where
dependency vendoring is in use.
This change modifies gin's unit tests to allow such paths.

tests: make path assertions aware of vendoring

---

gin_test.go

Fixes #550, change a duplicate assert on the Path of the route by an assert on Handler name associated with the route.

Fix typo on gin_test.go

---

context.go

Fixes typo from 'If Parses' to 'It parses'

[Cleanup] Typo in context.go

---

context.go
context_test.go
logger.go
logger_test.go
recovery_test.go

Otherwise, caller needs to invoke WriteHeaderNow himself after
AbortWithStatus(), which is error-prone.
Also modified ErrorLoggerT() such that it always writes log to response
body. Otherwise calling AbortWithStatus() will fail to write body because
c.Writer.Written() is set true by WriteHeaderNow().
It addresses #585

Write header immediately in AbortWithStatus()

---

mode.go

Quote from docs
> DefaultWriter is the default io.Writer
But DefaultWriter has type `*os.File`, so i can't run code like this:
```
package main
import (
"io/ioutil"
)
func main() {
gin.DefaultWriter = ioutil.Discard
}
```
```
$ go run main.go 
./main.go:9: cannot use ioutil.Discard (type io.Writer) as type *os.File in assignment: need type assertion
```
It broke in [this](https://github.com/gin-gonic/gin/commit/9e930b9bdd5a29bac38fb491ffac4e7ea84b825d#diff-fd98eaa389d204eaf86f6913742c7551L34) commit

Default writers must be io.Writers

---

logger.go

Here's a little improvement to the default logger so that the output isn't colorised if we're not outputting to a terminal. So, if we run with `./server | tee my.log` then instead of my log file looking like this:
```
[GIN] 2016/11/17 - 16:28:44 |^[[97;42m 200 ^[[0m|   24.459651ms | ::1 |^[[97;44m  ^[[0m GET     /
[GIN] 2016/11/17 - 16:28:44 |^[[97;42m 200 ^[[0m|  1.766299995s | ::1 |^[[97;44m  ^[[0m GET     /ws
[GIN] 2016/11/17 - 16:28:44 |^[[97;42m 200 ^[[0m|   11.265361ms | ::1 |^[[97;44m  ^[[0m GET     /static/favicon.gif
```
It looks like this:
```
[GIN] 2016/11/17 - 16:28:44 | 200 |   24.459651ms | ::1 |   GET     /
[GIN] 2016/11/17 - 16:28:44 | 200 |  1.766299995s | ::1 |   GET     /ws
[GIN] 2016/11/17 - 16:28:44 | 200 |   11.265361ms | ::1 |   GET     /static/favicon.gif
```
The …

Logger: skip ANSI color commands if output is not a tty

---

context.go
context_test.go

For scenarios like this:
``` go
// POST /?[]foo_ids=1&[]foo_ids=3&[]foo_ids=5
c.PostFormArray("[]foo_ids") // []string{"1", "3", "5"}
```

Implement QueryArray and PostFormArray methods

---

logger.go

**critical issue #752**
Please help to review.
cc @javierprovecho @tboerger 

fix #752 ignore appengine os.

---

.travis.yml
logger.go

Fixed #744 
Fixed #752 
Fixed #753 
cc @javierprovecho @tboerger @aviddiviner @kujenga

Support google appengine for IsTerminal func.

---

README.md

Hi!
This pull request removes the obsolete func (`LoadHTMLTemplates`) in README.

Remove an obsolete func in README

---

logger.go

`reset` field should be after `method` in LoggerWithWriter function.

fix default log format

---

context.go
context_test.go

The only reason to import "golang.org/x/net/context" package is to check that `*gin.Context` implements `context.Context` interface. But this implies fetching whole "golang.org/x/net" package tree using `go get`. So moving this check to `context_test.go` is reasonable.
This also resolves issues #469 and #684.

Move golang.org/x/net/context.Context interface implementation check to tests

---

context.go

Golang spec says: a nil map is equivalent to an empty map except that no elements may be added.

Context.Get() does not need to test whether Keys is nil or not

---

README.md
examples/basic/main.go
logger.go
logger_test.go

Fixed #769 
```go
package main
import (
)
func main() {
// Disable Console Color
gin.DisableConsoleColor()
// Ping test
r.GET("/ping", func(c *gin.Context) {
c.String(200, "pong")
})
}
```

Support disable console color

---

context.go
context_test.go

Fixed #774 
```go
package main
import (
"log"
"net/http"
)
func main() {
router.POST("/upload", func(c *gin.Context) {
// single file
file, _ := c.FormFile("file")
log.Println(file.Filename)
c.String(http.StatusOK, "Uploaded...")
})
router.Run(":8080")
}
```
curl command:
```sh
curl -X POST http://localhost:8080/upload -F "file=@/Users/mtk10671/z.sh" -H "Content-Type: multipart/form-data"
```
```go
package main
import (
"log"
"net/http"
)
func main() {
router.POST("/upload", func(c *gin.Context) {
// Multipart form
form, _ := c.MultipartForm()
files := form.File["upload[]"]
for _, file := range files {
log.Println(file.Filename)
}
c.String(http.StatusOK, "Uploaded...")
}) …
```

Support upload single or multiple files.

---

context.go
context_test.go

Hey, here's an addition to `gin.Context` to allow easy checks of whether the client requested a websocket upgrade, so you can handle things cleanly.
```go
app.GET("/", func(c *gin.Context) {
if c.IsWebsocket() {
// Websocket request, so we can do something like:
melody.HandleRequest(c.Writer, c.Request)
return
}
// No websockets required, serve normally.
c.HTML(http.StatusOK, ...)
}
```

Add convenience method to check if websockets required

---

context.go
context_test.go

Use X-Forwarded-For before X-Real-Ip as Nginx uses X-Real-Ip with the proxy's IP.
fix #692 testing.

update get client ip func

---

context.go

Simple english typos in the Copy() method

Fixed typos in Context

---

gin.go

Dear gin committers, thanks for your great and awesome work. Unfortunately i've hit a corner case to which i didn't find a sufficient solution and would like to share my fix with the community.
We are rewriting a large pile of fu^Wold PHP Code from a project i just was put upon. The problem being that this is highly SEO-crap-stuff that the URLs that have been used in the past, need to work exactly like they are, because they have been pimped, yadda yadda blah.
Anyway, i could not convince them that using a better URL Scheme with 3xx would be probably better. So technically the problem is that they have URLs with multiple parameters within one /-segment. Imagine /:categoryName-at-:city . Now since i have all the categories and cities in the database, i tried adding them all, but that didnt …

Added HandleContext to re-enter soft-rewritten Requests.

---

binding/form_mapping.go
context_test.go

It's required to inform the format:
```go
type T struct{
Time time.Time `form:"a_time" time_format:"02/01/2006"`
}
```
The default location is `time.Local`. If a `utc` tag is given, localtion is `time.UTC`:
```go
type T struct{
Time time.Time `form:"a_time" time_format:"02/01/2006" utc:"1"`
}
```
If user input is blank (`""`), then `form.Time.IsZero()` will return `true`.

Support time.Time on form binding

---

gin.go
routes_test.go
tree.go
tree_test.go

Fix for #777, #640, #722.
Another try to make it faster into master :)
Almost same as #777 but handles one more case in tree.getValue.
@appleboy Please review it. With this (plus forcing UseRawPath) the drone became handling escaped params. Thanks!
Replaces #803

The url.RawPath used when engine.UseRawPath is set to true.

---

binding/form_mapping.go

If a empty string is given(`""`), them time should be zero.

Fix time.Time binding

---

context.go
deprecated.go

feat(context): add idiomatic binding functions for clear err managment

---

fixtures/basic/raw.tmpl
gin.go
gin_test.go
render/html.go

Now templates (function maps for helpers) can be better configured and we can keep the reload on request of the templates.

Made funMaps for the templates configurable and hot-reloadable

---

debug_test.go

Sometimes travis will build error because `TestDebugPrintLoadTemplate` templates print-order not guaranteed.
travis ref:
- https://travis-ci.org/gin-gonic/gin/jobs/249505506
- https://travis-ci.org/gin-gonic/gin/jobs/249296346
- https://travis-ci.org/gin-gonic/gin/jobs/249505506

fix(tests): TestDebugPrintLoadTemplate use assert.Regep instead of assert.Equal

---

auth.go
errors.go
fs.go
gin.go
response_writer.go
routergroup.go

I have read some source codes of official go, I not found it use nesting `type` to define `struct` or `interface`, so commit this pr, thanks!
And it's better to avoid unnecessary indentation.

separate type define

---

context.go
context_test.go
gin.go
render/json.go
render/render.go
render/render_test.go

Implement https://github.com/gin-gonic/gin/issues/433, `SecureJSON` default prepends "while(1)," to response body if the given struct is array values. Examples are shown below:
```go
package main
import (
"net/http"
)
func main() {
r.SecureJsonPrefix(")]}',\n")  // Default "while(1);"
r.GET("/someJSON", func(c *gin.Context) {
fruit := []string{"apple", "peach", "pear"}
// Will output  :   while(1);["apple","peach","pear"]
c.SecureJSON(http.StatusOK, fruit)
})
r.Run(":8080")
}
```
Please review and advise, thanks.

feat: add SecureJSON func to prevent json hijacking

---

binding/json.go
context_test.go
errors.go
errors_test.go
render/json.go
vendor/vendor.json

A high-performance 100% compatible drop-in replacement of "encoding/json"
https://github.com/json-iterator/go
cc @javierprovecho @tboerger 

feat: change json lib to jsoniter

---

.travis.yml

I want to send it from the test with travis-ci before sending a pull request.
In the case of gin, it is an error to test the repository that was fork in travis-ci.
https://travis-ci.org/178inaba/gin/jobs/105072041
This is I think because there is assumed test the import path "github.com/gin-gonic/gin".
So, we added a setting to fix the import path of golang set of travis-ci.
When you add test of travis-ci was movement successfully.
https://travis-ci.org/178inaba/gin/jobs/105225833
PS Thank you for always maintains a gin.

add import path to .travis.yml

---

binding/json.go
mode.go
mode_test.go

resolve #368  
I added an option EnableJsonDecoderUseNumber, so that you can choose whether or not to enable UseNumber in the JSON decoder.
Please review.

resolve #368 add option to UseNumber() in gin.Context.BindJSON()

---

logger.go
logger_test.go

show query string in logger.

---

README.md
context.go
context_test.go
examples/upload-file/multiple/main.go
examples/upload-file/single/main.go

ref https://github.com/gin-gonic/gin/issues/674

feat(context): add SaveUploadedFile func.

---

BENCHMARKS.md
README.md

fix https://github.com/gin-gonic/gin/pull/1013
cc @javierprovecho @thinkerou 
The GitHub API is rather large, consisting of 203 routes. The tasks are basically the same as in the benchmarks before.
Benchmark name 					| (1) 		| (2) 		| (3) 		| (4)
--------------------------------|----------:|----------:|----------:|------:
BenchmarkAce_GithubAll                     | 10000            | 134059           | 13792        | 167
BenchmarkBear_GithubAll                     | 5000            | 534445           | 86448        | 943
BenchmarkBeego_GithubAll                    | 3000            | 592444           | 74705        | 812
BenchmarkBone_GithubAll                      | 200           | 6957308          | 698784       | 8453
BenchmarkDenco_GithubAll                   | 10000            | …

feat(Benchmark): update benchmark data

---

README.md
binding/binding.go
binding/binding_test.go
binding/query.go
context.go
context_test.go

see https://github.com/gin-gonic/gin/issues/742#issuecomment-268944445 , only parse/bind the query string params

feat(context): add BindQuery func

---

logger.go

updated before：
upupdated after：

not display color when set disableColor

---

context.go

Keys need to be canonicalized via `textproto.CanonicalMIMEHeaderKey()`.
fix #1079

Use standard library for retrieving header

---

README.md
binding/binding.go
binding/default_validator.go
binding/validate_test.go
examples/custom-validation/server.go

`validator` allows for registration of custom validation tag - http://godoc.org/gopkg.in/go-playground/validator.v8#Validate.RegisterValidation. This adds a method to the `StructValidator` interface and implements the same in `defaultValidator`. I also added an example to the readme.

feat: Add support for custom validation tags

---

README.md
context.go
examples/upload-file/multiple/main.go
examples/upload-file/single/main.go
gin.go

Currently there is no option to set the amount of memory the http.Request is allocating when ParseMultipartForm is called, other than the const value 'defaultMemory'.
This PR moves that constant value from the Context to the Engine, so that a different value can be set.
Examples and README.md has been updated accordingly.

Moved const 'defaultMemory' to attrib. Engine.MaxMultipartMemory instead.

---

binding/form_mapping.go
context_test.go

ref #801
This enables to specify the location to `time.Time` type in form binding.  It uses `time_location` tag.
```go
type T struct{
Time time.Time `form:"a_time" time_format:"02/01/2006" time_location:"Asia/Tokyo"`
}
```

Support time location on form binding

---

README.md
context.go
context_test.go

Currently, the functions `ctx.Bind`, `ctx.BindJSON`, `ctx.BindQuery` all use `ctx.MustBindWith`.
In my opinion, the current implementation of `ctx.MustBindWith` has the following drawbacks. Note that this has been discussed before and I am including it here to avoid needing to crawl multiple issues, threads:
- **Lack of control**
- It sets the HTTP status code as 400 and developer cannot set any other HTTP status code(ex: 422, `http.StatusUnprocessableEntity`)
- It aborts the handler chain. Developer should be able to decide whether the resulting error is worth aborting or can be reconciled.
- Cannot use repeated `Bind` as discussed in #811. Developer might want to bind query params and JSON body separately.
- **Possibly incorrect `Content-type` header** 
- It sets the `Content-type` as …

ShouldBind counterparts for Bind methods

---

context.go

I came across this while going through the [documentation of Bind](https://godoc.org/github.com/gin-gonic/gin#Context.Bind).

Doc: Fix typo in documentation of Bind

---

mode.go
mode_test.go

Not setting mode explicitly sets gin into debug mode, but it does not
make it possible to retrieve gin mode as Debug since it's set to "".
Calling `gin.Mode()` returns "" even though gin is in debug mode.
The alternative approach is to change SetMode to not accept "" and make `init` function calling `SetMode(DebugMode)` explicitly when the mode is not defined. That would definitely change how SetMode reacts to inputs and could break some apps.

Make "" mode being the same as debug mode

---

README.md
examples/graceful-shutdown/graceful-shutdown/server.go

In "graceful-shutdown" examples, ListenAndServe errors are checked but just to be logged.
If port is already used by another program, program will start, fail to bind, but still run, waiting for a sigterm.
Also handling error "ErrServerClosed" which is triggered by Shutdown and should be considered as a legit error.

doc(graceful-shutdown): failure to ListenAndServe should be a reason to exit

---

recovery.go

I found that gin printed the current stack information in panic, but there was no time to print panic, and it was hard to know when the panic occurred.

add gin panic time log

---

README.md
binding/binding.go
binding/default_validator.go
binding/json.go
binding/validate_test.go
examples/custom-validation/server.go
examples/struct-lvl-validations/README.md
examples/struct-lvl-validations/server.go

- Add func `ValidatorEngine` for returning the underlying validator engine used
in the default `StructValidator` implementation.
- Remove the function `RegisterValidation` from the `StructValidator` interface
which made it immpossible to use a `StructValidator` implementation without the
`validator.v8` library.
- Update and rename test for registering validation
`Test{RegisterValidation => ValidatorEngine}`.
- Update readme and example for registering custom validation.
- Add example for registering struct level validation.
- Add documentation for the following binding funcs/types:
- `Binding` interface
- `StructValidator` interface
- `Validator` instance
- `Binding` implementations
- `Default` func
Closes #1147, #1211.

fix(binding): Expose validator engine used by the default Validator

---

examples/app-engine/README.md

The App Engine SDK is superseded by the Cloud SDK, so goapp is now deprecated.
To avoid confusion, how about changing the instruction?

change README for app-engine example because of goapp deprecation  

---

README.md
context.go
context_test.go
render/json.go
render/render.go
render/render_test.go

Jsonp is common format in json to o request data from servers  in  different domains, 
I added Jsonp's data return format.

Add Jsonp Support to Context

---

binding/binding_test.go
binding/form_mapping.go

Useful in case if you need to bind the form to the following structure:
```
type input struct {
Field *string `form:"field" binding:"omitempty,max=128"`
}
```

Add support of pointers in form binding

---

README.md
binding/binding.go
binding/binding_body_test.go
binding/json.go
binding/msgpack.go
binding/protobuf.go
binding/xml.go
context.go
context_test.go

close #216 
#216 says some formats in requests' body cannot be bound into different structs by calling multiple times.
```go
type modelA struct {
Foo string `form:"foo" json:"foo" binding:"required"`
Bar int64  `form:"bar" json:"bar" binding:"required"`
}
type modelB struct {
Hoge string `form:"hoge" json:"hoge" xml:"hoge" binding:"required"`
Fuga int64  `form:"fuga" json:"fuga" xml:"fuga" binding:"required"`
}
func main() {
r := gin.New()
r.POST("/json", func(c *gin.Context) {
fa, fb := modelA{}, modelB{}
if aerr := c.ShouldBindWith(&fa, binding.JSON); aerr == nil {
c.JSON(http.StatusOK, gin.H{"form": fa})
} else if berr := c.ShouldBindWith(&fb, binding.JSON); berr == nil {
c.JSON(http.StatusOK, gin.H{"form": fb})
} else {
c.AbortWithStatusJSON(
http.StatusBadRequest,
gin.H{
"errors": …
```

Fix #216: Enable to call binding multiple times in some formats

---

binding/binding_test.go
binding/form_mapping.go

Hello all, I find a bug in gin.
Reproduce this like below:
```
type A struct {
INum int64 `form:"numvalue"`
}
type B struct {
IBool bool `form:"boolvalue"`
}
func handleParaNum(c *gin.Context) {
var a A
err := c.ShouldBindQuery(&a)
if err != nil {
c.String(200, "cause an err=%s", err.Error())
} else {
c.String(200, "bind ok")
}
return
}
func handleParaBool(c *gin.Context) {
var b B
err := c.ShouldBindQuery(&b)
if err != nil {
c.String(200, "cause an err=%s", err.Error())
} else {
c.String(200, "bind ok")
}
return
}
func main() {
route := gin.Default()
route.GET("/test_error_num", handleParaNum)
route.GET("/test_error_bool", handleParaBool)
route.Run(":8085")
}
```
And tow cmds, 
```
[root@localhost ~]# curl localhost:8085/test_error_num?numvalue=3s   
cause an err=strconv.ParseInt: …
```

fix bug, return err when failed binding bool

---

README.md
context.go
context_test.go
render/reader.go
render/render.go
render/render_test.go

This pull request adds a new method called `DataFromReader` to provides an easy way to serve dynamic files.

Serve easily dynamic files with `DataFromReader` context method

---

README.md
gin.go

Reference this issue #1323 
1. There isn't any eg about `HandleContext`  
2. The `c.Request.Path`  of `HandleContext` Comment  is not right   
Based on the above two points, I pull this request.  
If you think it's unnecessary, I will close this.  
Thx.

Add and fix the explanation of `HandleContext`

---

utils.go

And I test them benchmark:
code:
```go
package stringsbench
import "strings"
func index(part string) string {
if index := strings.IndexByte(part, ';'); index >= 0 {
if part := strings.TrimSpace(strings.Split(part, ";")[0]); part != "" {
return part[0:index]
}
}
return ""
}
func split(part string) string {
return strings.Split(part, ";")[0]
}
```
```go
package stringsbench
import (
"testing"
)
func BenchmarkIndex(b *testing.B) {
b.RunParallel(func(pb *testing.PB) {
for pb.Next() {
index("text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,image/apng,*/*;q=0.8")
}
})
}
func BenchmarkSplit(b *testing.B) {
b.RunParallel(func(pb *testing.PB) {
for pb.Next() {
split("text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,image/apng,*/*;q=0.8")
}
})
}
```
And the result: …

utils:  use strings.Split instead of strings.IndexByte

---

response_writer.go
response_writer_test.go

The status of responseWriter will be overwrite if flush was called. This is caused by the Flush of http.response.Flush().

flush operation will overwrite the origin status code

---

README.md

"not match neither" means that it will match.

Remove: Double negative

---

README.md
context.go
context_test.go

Add BindXML AND ShouldBindXML #1484

Add BindXML AND ShouldBindXML #1484

---

binding/form_mapping.go

To make things working in line with `encoding/json` decoder, I'd suggest to set default time format as `time.RFC3339`.
```
type input struct {
Field time.Time `form:"field" json:"time"`
}
```
This will make values bound in the same way as if you are using structures as above and different bindings depending on the request type.

Set default time format in form binding

---

README.md

A little change in readme, nothing about code.

Update readme about the version of gin

---

json/jsoniter.go

add newencoder to fix compile error for -tags=jsoniter

fix compile error for -tags=jsoniter

---

vendor/vendor.json

#1491 adds some lib when upgrade json-iterator but it is not needed, and use `v1.1.5` not `1.1.5` version for json-iterator.

chore: update vendor version

---

context_test.go
debug.go
debug_test.go

fix https://github.com/gin-gonic/gin/issues/829
remove `log.SetFlags(0)`

feat: replace debug log with fmt package.

---

recovery.go
recovery_test.go

Fixes #1331
HTTP logging leaks sensitive request information.
This PR removes HTTP request logging during panics.

Don't log requests

---

logger.go
logger_test.go

1. Why is this change neccesary?
White text on a yellow background was illegible with most terminal color schemes
2. How does it address the issue?
The white text was replaced with a bash compatible dark gray while keeping the
yellow background colour
3. What side effects does this change have?
Resolves #1552
Before:
After:

Make logger use a yellow background and a darkgray text for legibility

---

debug.go
debug_test.go

feat: add go version judge when print debug warning log

---

debug.go

fix #1560 changes are breaking in App Engine.
cc @giulianobr @philippgille

fix: fmt output log to os.Stderr

---

gin.go
gin_integration_test.go

As per #1230 there is an issue when using HandleContext where the context of the request is returned to the context sync.Pool before the parent request has finished, causing context to be used in a non-thread safe manner.
I've removed the bug by not entering the context back in the pool and leaving that to ServeHTTP.
There was no test coverage for this function so I've also added the test to cover it. As the bug only happens when there are concurrent requests, the tests issues hundreds of concurrent requests. Without the bug fixed the tests do consistently recreate the error.

removed use of sync.pool from HandleContext and added test coverage

---

context.go
context_test.go

When `gin.Context.FormFile("...")` is called the `engine.MaxMultipartMemory` is never used. This PR makes sure that the `MaxMultipartMemory` is passed and removes 2 calls to `http.Request.ParseForm` since they are called from `http.Request.ParseMultipartForm`

Pass MaxMultipartMemory when FormFile is called

---

README.md

FIX r.LoadHTMLGlob("/path/to/templates")) to FIX r.LoadHTMLGlob("/path/to/templates")

FIX r.LoadHTMLGlob("/path/to/templates")

---

errors.go
mode.go

The following comments to vars, conts and method were added to pass  `golinter` with 100%.

Added some comments to avoid having golint warnings

---

README.md
examples/realtime-advanced/resources/room_login.templ.html
examples/realtime-chat/template.go

In XHTML, the <input> tag must be properly closed, like this `<input />`.  In HTML5 the `<input>` tag has no ending slash.  https://www.w3schools.com/tags/tag_input.asp

Change HTML input tags to use HTML5 syntax.

---

examples/realtime-advanced/resources/room_login.templ.html
examples/realtime-chat/template.go

The `<link>` element is an empty element, it contains attributes only. In HTML5 the `<link>` tag has no end tag. In XHTML the `<link>` tag must be properly closed.
https://www.w3schools.com/tags/tag_link.asp

Change HTML link tags to use HTML5 syntax.

---

README.md
binding/binding.go
binding/binding_body_test.go
binding/binding_test.go
binding/yaml.go
context.go
context_test.go

This adds binding support for YAML.
Sidenote: `testBodyBinding` uses `JSON.Bind` instead of the `Binding` instance passed as a parameter when testing the `badBody`. Is this intended?

Yaml binding

---

gin.go
gin_integration_test.go

Renewed the pr https://github.com/gin-gonic/gin/pull/526.
----
I use gin http.Server under [circus](http://circus.readthedocs.org/en/latest/) which is a socket manager.
I need to run http.Server through a file descriptor, so implemented `RunFd` method.
When using other socket managers (e.g. [einhorn](https://stripe.com/blog/meet-einhorn)), maybe work well.
``` go
package main
import (
"flag"
"github.com/yyoshiki41/gin"
)
var (
fd = flag.Int("fd", -1, "")
)
func main() {
flag.Parse()
// Ping test
r.GET("/ping", func(c *gin.Context) {
c.String(200, "pong")
})
// Method arg is the file descriptor number(int).
r.RunFd(*fd)
}
```
and, `circus.ini` example is below.
``` ini
[circus]
statsd = 1
[watcher:webapp]
cmd = ./main -fd $(circus.sockets.web)
numprocesses = 1 …
```

feat(server): Implements RunFd method

---

debug.go

Many debug logs have no line breaks, so fix them here.

Make sure the debug log contains line breaks

---

recovery.go
recovery_test.go

cc @justinfx please help me review, thanks!
ref: https://github.com/golang/go/blob/master/src/syscall/zerrors_linux_amd64.go

recovery: fix issue about syscall import on google app engine

---

binding/binding_test.go
binding/json.go

In the real world, it probably shouldn't matter. It just happened when I forgot to pass body to `http.NewRequest` and the function `Bind` panicked under that situation.
If we always assume body will not be nil, please let me know, I will close this PR. Thank you.

handle nil body for JSON binding

---

wercker.yml

Now the `wercker.yml` have no longer used.

chore: remove wercker yml file

---

binding/binding_test.go
recovery_test.go

now ci have the following output:
```
[GIN-debug] GET    /recovery                 --> github.com/gin-gonic/gin.TestPanicWithBrokenPipe.func1.1 (2 handlers)
--- FAIL: TestPanicWithBrokenPipe (0.00s)
--- FAIL: TestPanicWithBrokenPipe/Broken_pipe (0.00s)
recovery_test.go:111: 
Error Trace:	recovery_test.go:111
Error:      	"
2018/11/26 03:31:54 : : broken pipe
GET /recovery HTTP/1.1
" does not contain "Broken pipe"
Test:       	TestPanicWithBrokenPipe/Broken_pipe
--- PASS: TestPanicWithBrokenPipe/connection_reset_by_peer (0.00s)
=== RUN   TestResponseWriterReset
```
update after output:
```
=== RUN   TestPanicWithBrokenPipe
=== RUN   TestPanicWithBrokenPipe/broken_pipe
[GIN-debug] [WARNING] Running in "debug" mode. Switch to "release" mode in production.
- using env:	export GIN_MODE=release …
```

chore: fix test fail

---

.gitignore
Makefile

closes #1670 #1656 
please @appleboy review the scheme, and fail case have fixed #1669 , please first review and merge it, thanks!

ci: break when test fail

---

README.md
logger.go
logger_test.go

I want to define gin's log format.
Currently, instead of using the default Logger, I can define the log format by defining my own Logger function.
However, my own Logger function must include redundant codes similar to the default Logger.
ref. https://github.com/gin-gonic/gin/issues/1581
This PR solves the problem by adding new methods, `LoggerWithFormatter` and `LoggerWithConfig`.
example code
```
r := gin.New()
r.Use(Recovery())
r.Use(LoggerWithFormatter(func(param gin.LogFormatterParams) string {
// my own format
return fmt.Sprintf("[GIN] %v | %3d | %13v | %15s | %-7s  %s | %s\n%s",
param.TimeStamp.Format("2006/01/02 - 15:04:05"),
param.StatusCode,
param.Latency,
param.ClientIP,
param.Method,
param.Path,
SomeMyOwnParam(param.Request), // username or payload information …
```

Add LoggerWithFormatter method

---

context.go
githubapi_test.go

Add BindUri

---

context.go
context_17_test.go
context_pre17.go

*gin.Context implements standard context.Context methods, but always
returns data as context is still valid. Since Go 1.7, http.Request now
contains a context.Context object, which can be controlled by the
http.Server to indicates that the context is now closed, and persue of
request should be canceled.
This implements the propagation of http.Request context methods inside
gin.Context to have HTTP context cancelation information at gin.Context
level.
This is retro-compatible for Golang 1.6, and have no effect if http.Request have no context (as http.Request always provide context.Background is ctx is nil)

context: inherits context cancelation and deadline from http.Request context for Go>=1.7

---

README.md
examples/upload-file/multiple/main.go
examples/upload-file/single/main.go

I don't know if an example need a test

Fix #1693: file.Filename should not be trusted

---

logger.go
logger_test.go

In https://github.com/gin-gonic/gin/pull/1677, I  misspelled LoggerConfig's SkipPaths.
**Note**
This change breaks backward compability, but adding LoggerConfig is not released yet. This change affects only the user which is using master branch.

Plural is "Paths", not "Pathes"

---

binding/binding_test.go
binding/form.go
context.go
context_test.go
debug_test.go
errors_test.go
gin.go
gin_integration_test.go
githubapi_test.go
logger_test.go
middleware_test.go
recovery.go
render/json.go
render/protobuf.go
render/render_test.go
render/text.go
render/yaml.go
response_writer_test.go
routes_test.go

Fix all warnings after run `golangci-lint run --disable-all -E errcheck`
Fix #1738 #1247

fix errcheck warnings

---

context.go
context_test.go
gin_test.go
routes_test.go

If gin sometimes reset `Context.index` and `.handlers` then needs to recheck len of handlers every iteration on func `Context.Next()`:
https://github.com/gin-gonic/gin/blob/29a145c85dc0fafc3dd0ada62d856c4d95240010/context.go#L103-L111
---
Fix #1678, because gin change `c.handlers` when error on open file.
https://github.com/gin-gonic/gin/blob/29a145c85dc0fafc3dd0ada62d856c4d95240010/routergroup.go#L195-L202
---
Fix #1744, because gin reset `c.handlers` slice on `HandleContext()` func.
https://github.com/gin-gonic/gin/blob/29a145c85dc0fafc3dd0ada62d856c4d95240010/gin.go#L354-L360
https://github.com/gin-gonic/gin/blob/29a145c85dc0fafc3dd0ada62d856c4d95240010/context.go#L67-L75

fix Context.Next() - recheck len of handlers every iteration

---

logger.go

Fix the bug of issue https://github.com/gin-gonic/gin/issues/1746.
PR https://github.com/gin-gonic/gin/pull/1677 caused it.

Fix not to pass formatted string to Fprintf's format specifier parameter

---

gin.go
gin_test.go

Fix #1760
We need to restore `c.index` value after recursive handle an another path.

fix many redirects (#1760)

---

debug_test.go
deprecated_test.go
gin_test.go
githubapi_test.go
recovery_test.go

There are many tests write debug info to `os.Stderr`. And after that is hard to inspect failed tests.
Now I see only logs of failed tests.

Make silent debug info on tests

---

README.md
logger.go
logger_test.go

Add a function `ForceConsoleColor`, like `DisableConsoleColor` but to force coloring the output.
It usefull when some IDE's integrated console (like IntelliJ or Goland) are not detected as TTY, but can display colors.
Also helps if one want to output color in log file (#1590) and as a workaround for #1547.

Add a function to force color in console output

---

Makefile

before:
```
/tmp/go-build038919107/github.com/gin-gonic/gin/_test/_obj_test/context.go:719:11: unknown field 'SameSite' in struct literal of type http.Cookie
FAIL	github.com/gin-gonic/gin [build failed]
The command "make test" exited with 0.
```
And
```
package github.com/gin-gonic/gin/render (test)
imports github.com/stretchr/testify/assert
imports github.com/pmezard/go-difflib/difflib: cannot find package "github.com/pmezard/go-difflib/difflib" in any of:
/home/travis/gopath/src/github.com/gin-gonic/gin/vendor/github.com/pmezard/go-difflib/difflib (vendor tree)
/home/travis/.gimme/versions/go1.8.7.linux.amd64/src/github.com/pmezard/go-difflib/difflib (from $GOROOT)
/home/travis/gopath/src/github.com/pmezard/go-difflib/difflib (from $GOPATH)
FAIL	github.com/gin-gonic/gin/render [setup …
```

chore: fix Make script when failed

---

logger.go

Here is a change to make the response body size an available log formatter param.

Add response size to LogFormatterParams

---

logger.go
logger_test.go

Fix https://github.com/gin-gonic/gin/issues/1768

Change color methods in using defaultLogger function to public

---

context_test.go

Fix test errors on go master branch. #1784

fix #1784: correct error comparison on tests

---

README.md

After https://github.com/gin-gonic/gin/pull/1778, all examples link in README.md are dead

Update examples link in README after split examples PR is merged

---

README.md

Remove the link that doesn't use gin anymore. See the https://github.com/drone/drone/blob/20c19bc522abacc6072c566b6a4bd7cc3d19c2a6/go.mod#L29-L30

Drone switch from gin to go-chi in 1.0 version.

---

routergroup.go
routes_test.go

Fix: https://github.com/gin-gonic/gin/issues/1804
`allNoRoute` contains middlewares such as `gin.Logger`, `gin.Recovery`, so on.  The correct code is to use `noRoute`.
cc: @MetalBreaker

fix #1804 which is caused by calling middleware twice.

---

logger.go
logger_test.go

Truncate Latency precision in long running request

---

binding/form.go
binding/form_mapping.go

Refactor mapping to interface `setter` - for supporting a multipart request.
Benchmarks of a simple form mapping (with many fields and one field respectively):
```
⇒  benchcmp old.bch new.bch
benchmark                  old ns/op     new ns/op     delta
BenchmarkMapFormFull-4     2332          2358          +1.11%
BenchmarkMapFormName-4     218           235           +7.80%
benchmark                  old allocs     new allocs     delta
BenchmarkMapFormFull-4     12             12             +0.00%
BenchmarkMapFormName-4     1              1              +0.00%
benchmark                  old bytes     new bytes     delta
BenchmarkMapFormFull-4     200           200           +0.00%
BenchmarkMapFormName-4     8             8             +0.00%
```

refactor(form_mapping.go): mapping multipart request

---

recovery.go
recovery_test.go

This PR replaces the contents of that header with a *. This prevents
credential leak in logs.

Remove contents of the Authorization header while dumping requests

---

README.md

Fix a typo syscanll.SIGTERM -> syscall.SIGTERM

---

debug.go
debug_test.go

Aligns behaviour according to documentation.
Closes #1890.

Use DefaultWriter and DefaultErrorWriter for debug messages

---

binding/binding_test.go
binding/form_mapping.go

``` golang
package main
import (
)
type appkey struct {
Appkey string `json:"appkey" form:"appkey"`
}
type Query struct {
Page int `json:"page" form:"page"`
Size int `json:"size" form:"size"`
appkey
}
func main() {
router.POST("/login", func(c *gin.Context) {
var q2 Query
if c.ShouldBindQuery(&q2) == nil {
c.JSON(200, &q2)
}
})
router.Run(":8088")
}
```
http client:
old:
``` bash
curl -X POST "127.0.0.1:8088/login?appkey=china&page=1&size=10"
{"page":1,"size":10,"appkey":""}
```
now:
``` bash
curl -X POST "127.0.0.1:8088/login?appkey=china&page=1&size=10"
{"page":1,"size":10,"appkey":"china"}
```

Now you can parse the inline lowercase start structure

---

binding/form_mapping.go
context.go
tree.go

* strings.ToLower comparison changed to strings.EqualFold.
* Rewrite switch statement with only one case as if.

Some code improvements

---

context.go

See the benchmark results:
```
$ go test -benchmem -run=^$ github.com/gin-gonic/gin -bench ^BenchmarkGetQueryMap
goos: darwin
goarch: amd64
pkg: github.com/gin-gonic/gin
BenchmarkGetQueryMapOld-4        1000000              1810 ns/op             880 B/op         11 allocs/op
BenchmarkGetQueryMapNew-4        3000000               404 ns/op             336 B/op          2 allocs/op
PASS
ok      github.com/gin-gonic/gin        4.442s
```

chore: improve GetQueryMap performance.

---

context.go

benchmark program:
```go
func BenchmarkGetPostFormArrayNew(b *testing.B) {
c, _ := CreateTestContext(httptest.NewRecorder())
c.Request = createMultipartRequest()
var obj struct {
Foo          string    `form:"foo"`
Bar          string    `form:"bar"`
BarAsInt     int       `form:"bar"`
Array        []string  `form:"array"`
ID           string    `form:"id"`
TimeLocal    time.Time `form:"time_local" time_format:"02/01/2006 15:04"`
TimeUTC      time.Time `form:"time_utc" time_format:"02/01/2006 15:04" time_utc:"1"`
TimeLocation time.Time `form:"time_location" time_format:"02/01/2006 15:04" time_location:"Asia/Tokyo"`
BlankTime    time.Time `form:"blank_time" time_format:"02/01/2006 15:04"`
}
c.Bind(&obj)
for i := 0; i < b.N; i++ {
c.GetPostFormArray("array")
}
}
```
result:
```
$ go test …
```

feat: improve get post data.

---

README.md
binding/form.go
binding/multipart_form_mapping.go
binding/multipart_form_mapping_test.go

Fix #1878
Add support multi files on bind multipart requests.
Example:
```
type s struct {
Files []*multipart.FileHeader `form:"files"`
}
```

binding: add support of multipart multi files (#1878)

---

README.md
binding/binding.go
binding/binding_test.go
binding/form_mapping.go
binding/header.go
context.go
context_test.go

update #1956
```go
package main
import (
"fmt"
)
type testHeader struct {
Rate   int    `header:"Rate"`
Domain string `header:"Domain"`
}
func main() {
r.GET("/", func(c *gin.Context) {
h := testHeader{}
if err := c.ShouldBindHeader(&h); err != nil {
c.JSON(200, err)
}
fmt.Printf("%#v\n", h)
c.JSON(200, gin.H{"Rate": h.Rate, "Domain": h.Domain})
})
r.Run()
// client
// curl -H "rate:300" -H "domain:music" 127.0.0.1:8080/
// output
// {"Domain":"music","Rate":300}
}
```

support bind http header param #1956

---

README.md

* fix README.md code bug
``` go
func main() {
// r.GET("/JSONP?callback=x", func(c *gin.Context) { // old
r.GET("/JSONP", func(c *gin.Context) {    // new
data := gin.H{
"foo": "bar",
}
//callback is x
// Will output  :   x({\"foo\":\"bar\"})
c.JSONP(http.StatusOK, data)
})
// Listen and serve on 0.0.0.0:8080
r.Run(":8080")
}
// client
// curl http://127.0.0.1:8080/JSONP?callback=x
// old output
// 404 page not found
// new output
// x({"foo":"bar"})
```
* change map[string]interface{} to gin.H
Most of the sample code in the documentation map[string]interface{} is represented by gin.H.
gin.H is a very important place for me to like gin, can write a lot less code

fix README.md code bug and Change map to gin.H

---

.travis.yml
README.md
debug.go
debug_test.go

Here are the updates for fix #1912

Drop Support for go1.8 and go1.9

---

routes_test.go
tree.go

* worked with more complex situations
* the original pr not work when add a short route with the same prefix
to some already added routes

Bugfix for the FullPath feature

---

debug.go
errors.go

Go1.10's strings.Builder structure saves memory
This is its implementation principle
```go
// String returns the accumulated string.
func (b *Builder) String() string {
return *(*string)(unsafe.Pointer(&b.buf))
}
```

Gin1.5 bytes.Buffer to strings.Builder

---

gin.go
render/render_test.go

- Use buf.String instead of converison
- Remove redundant return

Simplify code

---

render/render_test.go

- Fixed : Adjust the correct test case, the source code is to `pinic`,  but test case is not correctly captured
- Add : Add the test case of code 201
**[The original PR](#2014 )**

Adjust Render.Redirect test case

---

README.md

Previous version of Readme's multiple services case had issues: if one service did not start for any reason, you would never know about it.

Updated Readme.md for serving multiple services

---

README.md

If you try to use `loadTemplate()` several times, every time except first will fail.

Updated Readme.md: file.Close() for template read

---

CHANGELOG.md
README.md

Fix spelling.

---

binding/form_mapping.go

according to https://github.com/golang/go/wiki/CodeReviewComments#error-strings, Error strings should not be capitalized.

format errUnknownType

---

binding/binding_test.go
binding/form_mapping_benchmark_test.go
gin.go
gin_integration_test.go
render/render_test.go

Fix 'errcheck' linter warnings

---

routergroup.go

Close files opened in static file handler

---

context.go

https://github.com/gin-gonic/gin/issues/2104
func (r *Request) FormFile(key string) (multipart.File, *multipart.FileHeader, error)
File is an interface to access the file part of a multipart message. Its contents may be either stored in memory or on disk. If stored on disk, the File's underlying concrete type will be an *os.File.

[FIX] c.Request.FormFile maybe file, need close

---

CHANGELOG.md
version.go

ready to release v1.5.0

---

mode.go

EnableJsonDisallowUnknownFields => EnableJsonDecoderDisallowUnknownFields

fix comment in `mode.go`

---

context_test.go
render/reader.go
render/reader_test.go

Fixed #2111 
Now is possible to call `c.DataFromReader` without extra headers.
```
c.DataFromReader(http.StatusOK, 5, gin.MIMEHTML, strings.NewReader("1234\n"), nil)
```
Thanks: @nikandfor

[FIX] allow empty headers on DataFromReader

---

README.md

Changed wording for clarity in README.md

---

gin.go
routes_test.go

See the detailed benchmark: https://github.com/gin-gonic/gin/pull/2153
before:
```
#GithubAPI Routes: 203
Gin: 58512 Bytes
#GPlusAPI Routes: 13
Gin: 4384 Bytes
#ParseAPI Routes: 26
Gin: 7776 Bytes
#Static Routes: 157
Gin: 34936 Bytes
goos: darwin
goarch: amd64
pkg: github.com/julienschmidt/go-http-routing-benchmark
BenchmarkGin_Param        	11682692	       107 ns/op	       0 B/op	       0 allocs/op
BenchmarkGin_Param5       	 5853684	       205 ns/op	       0 B/op	       0 allocs/op
BenchmarkGin_Param20      	 2497855	       484 ns/op	       0 B/op	       0 allocs/op
BenchmarkGin_ParamWrite   	 6599636	       180 ns/op	       0 B/op	       0 allocs/op
BenchmarkGin_GithubStatic 	 9790374	       125 ns/op	       0 B/op	       0 allocs/op
BenchmarkGin_GithubParam  	 4965781	       244 ns/op …
```

chore(performance): Improve performance for adding RemoveExtraSlash flag

---

tree.go

the pr includes three parts:
1. use `longestCommonPrefix`  from https://github.com/julienschmidt/httprouter/blob/master/tree.go#L20
2. remove `else` statement to reduce indent
3. sync the issue fixed https://github.com/julienschmidt/httprouter/issues/172
after:
```
➜  go-http-routing-benchmark git:(master) go test -bench=Gin
#GithubAPI Routes: 203
Gin: 58512 Bytes
#GPlusAPI Routes: 13
Gin: 4384 Bytes
#ParseAPI Routes: 26
Gin: 7776 Bytes
#Static Routes: 157
Gin: 34936 Bytes
goos: darwin
goarch: amd64
pkg: github.com/julienschmidt/go-http-routing-benchmark
BenchmarkGin_Param        	12134269	       100 ns/op	       0 B/op	       0 allocs/op
BenchmarkGin_Param5       	 6822183	       173 ns/op	       0 B/op	       0 allocs/op
BenchmarkGin_Param20      	 2442889	       479 ns/op	       0 B/op …
```

tree: sync part httprouter codes and reduce if/else

---

tree.go
tree_test.go

sync httprouter:
https://github.com/julienschmidt/httprouter/pull/261

Fixed a bug in the calculation of the maximum number of parameters

---

tree.go

from httprouter:
https://github.com/julienschmidt/httprouter/commit/e746cd609a26ce7237331c6edd57fc455462095e
https://github.com/julienschmidt/httprouter/commit/6289311caafefac132cb3583bdd8d85580c0aecc

tree: sync httprouter update

---

README.md

- Update fixed code.
- Fix incorrect date for testing & demo.

Fix "Custom Validators" example

---

README.md

Just update the go-validator version in README to v10.

upgrade go-validator to v10 for README

---

CHANGELOG.md
context.go

Fix spelling

---

.travis.yml
Makefile
binding/binding_msgpack_test.go
binding/binding_nomsgpack.go
binding/binding_test.go
binding/msgpack.go
binding/msgpack_test.go
render/msgpack.go
render/render.go
render/render_msgpack_test.go
render/render_test.go

This PR add a build tag `nomsgpack` to exclude heavy deps `github.com/ugorji/go/codec` that may be not needed for most project. The goal is to reduce the resulting binary size. This could maybe improve some performances but that not the goal so I haven't bench it.
I go for the no impact by default by using a negate tag so that without change it will not impact project depending on this lib.
~~I will try to provide some results of binary size based on https://github.com/gin-gonic/examples.~~ -> see [comment](https://github.com/gin-gonic/gin/pull/1852#issuecomment-481043187)
Should fix (or at least a mitigation to) #1847

Add build tag nomsgpack

---

path.go
path_test.go

Signed-off-by: Andy Pan <panjf2000@gmail.com>

Reuse bytes when cleaning the URL paths

---

context.go

This issue has been discussed here #1452, here #1690, here #1736, here #2029, in my opinion, wether current behavior will be changed or not, current documentation doesn't match with real behavior, so it (documentation) has to be changed.
This is my view of what it should look like.

Update docs on Context.Done(), Context.Deadline() and Context.Err()

---

path.go

Make the constant `stackBufSize` local since the go compiler will replace any occurrence with the const value and it only applies to the `cleanPath` function. 
Also to correct the last wrong sync by me and sync code with httprouter again:
https://github.com/julienschmidt/httprouter/blob/master/path.go#L22

path: sync code with httprouter

---

auth.go
binding/form_mapping.go
gin.go
internal/bytesconv/bytesconv.go
internal/bytesconv/bytesconv_test.go
render/json.go

Benchmark:
```
BenchmarkBytesConvBytesToStrRaw-4   	21003800	        70.9 ns/op	      96 B/op	       1 allocs/op
BenchmarkBytesConvBytesToStr-4      	1000000000	         0.333 ns/op	       0 B/op	       0 allocs/op
BenchmarkBytesConvStrToBytesRaw-4   	18478059	        59.3 ns/op	      96 B/op	       1 allocs/op
BenchmarkBytesConvStrToBytes-4      	1000000000	         0.373 ns/op	       0 B/op	       0 allocs/op
```

Use zero-copy approach to convert types between string and byte slice

---

README.md

Renew README to fit the modification of SetCookie method

---

logger.go
logger_test.go

Copy https://github.com/gin-gonic/gin/pull/2265 and fix the tests

Add mitigation for log injection

---

gin.go

The current handling of Unix sockets is not correct.
1) The service should not delete the socket before binding to it. If the socket exists, that implies another service is already listening on the socket.
2) The socket should instead be cleaned up at shutdown.
3) The permissions should NOT be world writable by default.
One of the main reasons to use sockets is for security. Using sockets allows you to lock access down to a specific unix group/user.However, due to the various use cases for unix sockets, it may be a good idea to accept a `net.Listener` interface, so that the socket can be configured before the server is started.

Unix Socket Handling

---

README.md

The initial purpose was to remove the dead code from the example. Still, I hooked up a few improvements as well, such as comments in the code and the text structure separating the usage of third-party libraries from the usage of the built-in packages to handle it manually.
I also changed the term "graceful stop" to graceful shutdown, which seems to be more common in the web, therefore, it would make it easier to find the text.
Related pull request https://github.com/gin-gonic/examples/pull/33

Improved the graceful shutdown and restart section and removed dead code

---

utils.go

Reverts gin-gonic/gin#2216 and fix #2292

Revert "fix accept incoming network connections"

---

context.go
context_test.go

Add set samesite in cookie.

---

context.go
context_test.go
go.sum

fix missing initial sync.RWMutex

---

README.md

update set cookie example

---

mode.go

I think this is more elegant。In switch-case，we don't need judge that `value` is `""`。

update:SetMode function

---

context.go
gin.go

fix #2350 
See the report: https://github.com/gin-gonic/gin/issues/2350
Change `*sync.RWMutex` to `sync.RWMutex`. See [the commet](https://github.com/gin-gonic/gin/pull/2305#discussion_r399993737)
Testing in my Macbook Pro
```
$ go get github.com/gin-gonic/gin@d5a42fc8ac93cebe42cde9c9b91a138358e4f99a
go: github.com/gin-gonic/gin d5a42fc8ac93cebe42cde9c9b91a138358e4f99a => v1.6.3-0.20200503042414-d5a42fc8ac93
go: downloading github.com/gin-gonic/gin v1.6.3-0.20200503042414-d5a42fc8ac93
$ go get github.com/julienschmidt/httprouter@master
go: github.com/julienschmidt/httprouter master => v1.3.1-0.20200114094804-8c9f31f047a3
go: downloading github.com/julienschmidt/httprouter v1.3.1-0.20200114094804-8c9f31f047a3
```
Benchmark Result:
```
BenchmarkEcho_Param              	12894638	        88.9 …
```

chore(performance): Change *sync.RWMutex to sync.RWMutex

---

README.md

old: https://godoc.org/github.com/gin-gonic/gin
new: https://pkg.go.dev/github.com/gin-gonic/gin?tab=doc

chore: update godoc address

---

render/text.go

testing repo: https://github.com/appleboy/web-framework-benchmark
script:
```sh
$ go get github.com/gin-gonic/gin@v1.6.3
$ go test -bench=. -benchtime=10s
```
result: 
```
BenchmarkGinStatic-8               23306             50344 ns/op            8283 B/op        157 allocs/op
BenchmarkGinGitHubAPI-8            16506             71542 ns/op           10801 B/op        203 allocs/op
BenchmarkGinGplusAPI-8            284379              4061 ns/op             685 B/op         13 allocs/op
BenchmarkGinParseAPI-8            153843              7657 ns/op            1361 B/op         26 allocs/op
```
script:
```sh
$ go get github.com/gin-gonic/gin@1bd5a8f
$ go test -bench=. -benchtime=10s
```
result: 
```
BenchmarkGinStatic-8              246488             46740 ns/op            9915 B/op …
```

chore: improve render string performance

---

context.go
gin.go
routes_test.go
tree.go
tree_test.go

1. Add `*Params` in context.
2. move `maxParams` counts to engine

Sync route tree to httprouter latest code

---

routes_test.go
tree.go

While using func `context.FullPath()`, I encountered an issue that it always returns previous registered parent path. It's fine when I change the registration order.
Example: 
```go
func (s *testSuite) registerTest() {
s.router.GET("/user/:id/status", s.processWithStatus())
s.router.GET("/user/:id", s.processWithID())
}
func (s *testSuite) processWithStatus() gin.HandlerFunc {
return func(c *gin.Context) {
logger.Infof("XXX - FullPath /user/:id/status ---> %s", c.FullPath())
return
}
}
func (s *testSuite) processWithID() gin.HandlerFunc {
return func(c *gin.Context) {
logger.Infof("XXX - FullPath /user/:id ---> %s", c.FullPath())
return
}
}
```
Result: 
```
XXX - FullPath /user/:id/status ---> /service/api/v1/user/:id/status
XXX - FullPath /user/:id ---> /service/api/v1/user/:id/status …
```

fix(tree): reassign fullpath when register new node which the same current node

---

tree.go
tree_test.go

```go
package convert
import (
"bytes"
"strings"
"testing"
)
var (
strColon = []byte(":")
strStar  = []byte("*")
)
func countParamsOld(path string) uint16 {
var n uint
for i := range []byte(path) {
switch path[i] {
case ':', '*':
n++
}
}
return uint16(n)
}
func countParamsNew(path string) uint16 {
var n uint
s := strToBytes(path)
n += uint(bytes.Count(s, strColon))
n += uint(bytes.Count(s, strStar))
return uint16(n)
}
var foo = strings.Repeat("/:param", 256)
func BenchmarkCountParamsOld(b *testing.B) {
for i := 0; i < b.N; i++ {
countParamsOld(foo)
}
}
func BenchmarkCountParamsNew(b *testing.B) {
for i := 0; i < b.N; i++ {
countParamsNew(foo)
}
}
```
```sh
goos: linux
goarch: amd64
BenchmarkCountParamsOld-48    	 3000000	      1751 ns/op	       0 B/op	       0 allocs/op …
```

chore(performance): improve countParams

---

tree.go

There are two same functions in github.com/gin-gonic/gin/internal/bytesconv.

Remove some functions that have the same effect as the bytes package

---

.gitignore
render/json.go

remove an unused type SecureJSONPrefix in render/json.go

remove a unused type SecureJSONPrefix

---

README.md

Refer to issue https://github.com/gin-gonic/gin/issues/444

Add a redirect sample for POST method

---

errors.go
fs.go
routergroup.go

json ->  jsonData, avoid conflicts with json package names
onlyfilesFS -> onlyFilesFS,  little camel-case

Rename some variables

---

README.md
recovery.go
recovery_test.go

CustomRecovery allows the user to control what happens in the case of a panic without having to re-implement the Recovery middleware

Add CustomRecovery builtin middleware 

---

README.md

old: [![GoDoc](https://godoc.org/github.com/gin-gonic/gin?status.svg)](https://pkg.go.dev/github.com/gin-gonic/gin?tab=doc)
new: [![GoDoc](https://pkg.go.dev/badge/github.com/gin-gonic/gin?status.svg)](https://pkg.go.dev/github.com/gin-gonic/gin?tab=doc)

README: Change badge to pkg.go.dev

---

binding/form_mapping.go

Function setTimeField calls strconv.ParseInt with bit size 0 when
parsing Unix time, which means it is equivalent to specifying 32 on
32-bit architectures. This causes the function to suffer from the year
2038 problem. To fix it and keep the behavior the same on both 32-bit
and 64-bit architectures, explicitly specify bit size 64.
I am not sure if I should add a test for this pull request. It only affects 32-bit systems, but the CI only tests 64-bit systems.

binding: avoid 2038 problem on 32-bit architectures

---

context.go
context_test.go

I have an endpoint that uses an optional query parameter via DefaultQuery(). 
In one unit test case I want to test the route with that parameter.
I write that test as
```go
w := httptest.NewRecorder()
c, _ := gin.CreateTestContext(w)
routeHandler(c)
```
And this panics when routeHandler() calls c.DefaultQuery() because c.Request == nil.

Prevent panic in Context.GetQuery() when there is no Request

---

context.go
context_test.go

Add GetUint and GetUint64 method on gin.context

---

README.md

Closing the response body after serving data from reader

docs:close the body of the response

---

context.go

Content-Disposition in the `Context.FileAttachment` method is not a MIME style, but a slight performance response that can be avoided.
benchmark test file: [https://github.com/eudore/eudore/blob/master/_example/textprotoHeader_test.go](https://github.com/eudore/eudore/blob/master/_example/textprotoHeader_test.go)

update content-disposition header to MIME-style

---

utils.go
utils_test.go

benchmark cmp result:
```
benchmark                   old ns/op     new ns/op     delta
BenchmarkParseAccept-12     362           176           -51.38%
benchmark                   old allocs     new allocs     delta
BenchmarkParseAccept-12     6              2              -66.67%
benchmark                   old bytes     new bytes     delta
BenchmarkParseAccept-12     224           128           -42.86%
```

use IndexByte replace Split to improve performance

---

recovery.go

fix: print headers without Authorization header on broken pipe

---

render/text.go

bencmp result
```
benchmark                     old ns/op     new ns/op     delta
BenchmarkReader_Render-12     581           545           -6.20%
benchmark                     old allocs     new allocs     delta
BenchmarkReader_Render-12     9              8              -11.11%
benchmark                     old bytes     new bytes     delta
BenchmarkReader_Render-12     1008          992           -1.59%
```

reduce allocs and improve the render `WriteString`

---

errors.go
errors_1.13_test.go

Implement `.Unwrap() error` method on type `Error`, to be compatible with stdlib `errors.Is()` and `erors.As()` functions.

implement ".Unwrap() error" on Error type (#2525)

---

.travis.yml

This reverts commit fca3f95d7cdfdef203c78f220b84118f44590512.
details: https://github.com/gin-gonic/gin/pull/2538#issuecomment-753717649
cc @kishorkunal-raj

Revert "Adding ppc64le architecture support on travis-ci (#2538)"

---

gin_integration_test.go

windows cannot use path `/tmp/unix_unit_test`

test: fixed the TestUnixSocket test on windows

---

mode.go

Before:
```
panic: gin mode unknown: development
goroutine 1 [running]:
github.com/gin-gonic/gin.SetMode(...)
/home/flatearther/go/packages/pkg/mod/github.com/gin-gonic/gin@v1.6.3/mode.go:61
github.com/gin-gonic/gin.init.0()
/home/flatearther/go/packages/pkg/mod/github.com/gin-gonic/gin@v1.6.3/mode.go:48 +0x16a
exit status 2
```
After:
```
panic: gin mode unknown: development (available mode: debug release test)
goroutine 1 [running]:
github.com/gin-gonic/gin.SetMode(...)
/home/flatearther/go/packages/pkg/mod/github.com/gin-gonic/gin@v1.6.3/mode.go:61
github.com/gin-gonic/gin.init.0()
/home/flatearther/go/packages/pkg/mod/github.com/gin-gonic/gin@v1.6.3/mode.go:48 +0x16a
exit status 2
```

"gin mode unknown" error: show available mode

---

debug.go
debug_test.go

error min support Go version compare with README.md

fix error gin support min Go version

---

README.md

…ce before the if statement on graceful shutdown

Fixes to the graceful shutdown example

---

auth.go

Fix #2226 
I've read discussion in #2226, but there are few reasons to consider on behalf of merge of this PR:
* It's pretty easy to fix it
* Even if Basic Auth should not be considered as a secure auth method, it will be often misused in the wild. It'll be hard to make people using basic auth middleware always make informed decision.
* There are cases like server to server integration via HTTPS where basic auth is just good enough.

basic auth: fix timing oracle

---

.travis.yml
AUTHORS.md
BENCHMARKS.md
CHANGELOG.md
CONTRIBUTING.md
README.md

chore: Deleted spaces

---

.travis.yml
binding/binding.go
binding/binding_msgpack_test.go
binding/binding_nomsgpack.go
binding/msgpack.go
binding/msgpack_test.go
context_appengine.go
errors_1.13_test.go
internal/json/json.go
internal/json/jsoniter.go
render/msgpack.go
render/render_msgpack_test.go

currently, CI fails on go master branch.
as mentioned in golang/go#41184 and golang/go#44505, Go will probably migrate to a more robust build constraints directive, as explained design doc:
https://golang.org/s/go-build-design
so, we should prepare for that:
for Go-1.17: add all //go:build directives
for Go-1.18: remove all // +build directives

build: convert to go:build directives

---

routes_test.go

There are duplicate `assert.Equal(t, name, c.Param("name"))` lines in `TestRouteParamsByName` and `TestRouteParamsByNameWithExtraSlash` in `routes_test.go`, so I remove them.

chore: remove duplicate test 'assert.Equal'

---

AUTHORS.md
CHANGELOG.md
README.md
tree.go
tree_test.go

This ports a PR I made to httprouter, https://github.com/julienschmidt/httprouter/pull/329.
It adds the ability to have route schemas like `/users/:name` and `/users/groups` without running into conflicts.
From https://github.com/julienschmidt/httprouter/pull/329:
> I updated the search tree, so that non-wildcard paths are resolved _before_ wildcard paths, but both can be valid children. For instance, now you can finally have `/users/roles/:role` and `/users/:id` at the same time without issue.
> 
> First, non-wildcard children are checked for matches. If those fail to match, then it tries the wildcard children routes. For existing compatible route configurations, there should be no (or negligible) performance impact. Many people prefer compact routes and expect a sort of precedence with …

Add mixed param and non-param paths (port of httprouter#329)

---

context_test.go

`HeaderMap` is deprecated and should avoid to use.
Ref: https://golang.org/pkg/net/http/httptest/#ResponseRecorder

Use `Header()` instead of deprecated `HeaderMap`

---

binding/json.go

use errors.New to replace fmt.Errorf will much better

use errors.New to replace fmt.Errorf will much better

---

README.md

Need to pass a string to `gin.H` to show a message correctly.

Fix example code of `Bind Uri`

---

README.md

I think this information is useful for users that don't use `MsgPack` rendering.

Add note about `nomsgpack` tag to the readme

---

logger.go

`Duration.Truncate` was added in Go 1.9 and Gin required Go version 1.13+ now.
So we can use `Duration.Truncate`.

Use `Duration.Truncate` for truncating precision

---

go.mod
go.sum

- fix some validator problems: 
- [Fix boolean support for required_if, required_unless and eqfield](https://github.com/go-playground/validator/pull/754)
- Fixed url_encoded validation regex not handling totally unescaped data

upgrade validator to v10.6.1

---

binding/multipart_form_mapping_test.go

`FileHeader.Size` was added in Go 1.9. So we can use it now.
https://golang.org/pkg/mime/multipart/#FileHeader

Check multipart file header size on test

---

context_test.go
gin.go
gin_integration_test.go

#2632 
https://github.com/gin-gonic/gin/pull/2675
#2675 causes the `engine.prepareTrustedCIDRS` to never execute if `gin` is not started via `gin.RUN()`.
this pr set `engine.TrustedProxies` and execute `engine.prepareTrustedCIDRS` For items that don't use `gin.RUN`
Our project uses `http.Handler` to start the service instead of `gin.Run`

set engine.TrustedProxies For items that don't use gin.RUN

---

context.go
context_test.go
gin.go

When proxying an app through Cloudflare, the user's real IP is set in the CF-Connecting-IP header. This is more convenient than having to manually maintain an allow-list of trusted proxies.
Reference: https://support.cloudflare.com/hc/en-us/articles/200170986-How-does-Cloudflare-handle-HTTP-Request-headers-

Get client IP when using Cloudflare

---

binding/form_mapping.go
binding/header.go
binding/multipart_form_mapping.go
render/json.go

1.setFormMap error of result
2.adjust code for TrySet
3.error export for type multipart.FileHeader
4.code style adjust
5.reflect code maping optimize

Optimize code adjust

---

binding/form.go
debug.go

optimize code and reduce code cyclomatic complexity

---

tree.go

updated comments for Get function for params

---

context.go
context_appengine.go
context_test.go
gin.go

Updated #2723 using an enum-like.
This also marks `AppEngine` as deprecated (note that we can't detect people using `AppEngine: false` because that's also the zero value, so we can only show an error message to people who set `AppEngine: true`).
This removes the `Cloudflare` property set in #2723, which was never released anyways.

Setting trusted platform using an enum-like

---

recovery.go

In `recovery.go`:
- Fix typo in `CustomRecovery` comments.
- Add comments for `timeFormat`.

fix typo and add comments

---

recovery.go

- Skip unnecessary variable assignment in `timeFormat`.

Skip unnecessary variable assignment in timeFormat

---

render/msgpack.go
render/render_msgpack_test.go

- Add comments in `render/msgpack.go`.
- Use `buf.String()` instead of `string(buf.Bytes())` according to [(S1030) go-staticcheck](https://staticcheck.io/docs/checks).

Use buf.String() instead of string(buf.Bytes())

---

binding/default_validator.go
binding/default_validator_benchmark_test.go
binding/default_validator_test.go

Improve `sliceValidateError.Error` performance using `switch` and `strings.Builder`.
- Avoiding `[]string` memory allocation.
- Using `strings.Builder` instead of `strings.Join`, one loop cycle is enough (`strings.Join` runs a loop internally).
- Add more test cases.

Improve `sliceValidateError.Error` performance

---

README.md
binding/form_mapping.go
binding/form_mapping_test.go

feat(binding): support custom struct tag

---

binding/binding.go
binding/binding_nomsgpack.go

update the version of go-playground/validator to v10.6.1 in the comment.

update the version of validator in the comment

---

context.go

- Use bit shift operation instead of division in `context.go`.
- Add constant comments.

Use bit shift operation instead of division

---

gin.go

- Use std `net/http` http method constant instead of raw string in `gin.go`.

Use std http method constant instead of raw string

---

routergroup_test.go

- Use relative value instead of hard coded number in `TestRouterGroupTooManyHandlers`.
- Also check the panic value in test.

Improve router group tests

---

context.go
context_test.go

base on comment https://github.com/gin-gonic/gin/pull/2751#issuecomment-867461945 in https://github.com/gin-gonic/gin/pull/2751
also fallback Context.Deadline() Context.Done() Context.Err() to Context.Request.Context()

fallback Context.Deadline() Context.Done() Context.Err() to Context.Request.Context()

---

README.md

1. c.FullPath() == "/user/:name/*action"
get following error:
evaluated but not used 
2. c.String(http.StatusOK, "The available groups are [...]", name)
get following error:
undefined: name

catch error from examples

---

.golangci.yml

The default timeout of 1m has been exceeded, this PR is fixing this issue.
See https://github.com/gin-gonic/gin/runs/3369288827
```
Timeout exceeded: try increasing it by passing --timeout option
```

chore(ci): golangci timeout

---

.golangci.yml

Delete deadcode exclude rules

---

context_1.16_test.go
context_1.17_test.go
context_test.go

error info please see #2828
closed #2828

Fix go1.17 test error

---

.github/workflows/gin.yml

chore: Add go1.17 for testing

---

context.go
context_test.go

While writing e2e tests I noticed that adding path params can be simplified further. 
Instead of appending params to the gin context like this:
`c.Params = append(c.Params, Param{Key: key,Value: value})`
The function `SetParam` will do the same but increase usability for writing e2e tests.

gin.Context.SetParam shortcut for e2e tests

---

binding/binding_test.go
binding/protobuf.go

Change-Id: I194f7010835974b489b497c6d1f1b4e47b99864e
Solve https://github.com/gin-gonic/gin/issues/2850

fix: check obj type in protobufBinding

---

README.md
context.go
context_test.go
gin.go
gin_integration_test.go
gin_test.go

Related issues: #2814 #2697 #2819 
Related pull requests: #2832 #2692 
About #2692 :
> This fix has 2 problems:
>
>1. it's not backward-compatible
>2. is doesn't update related documents
https://github.com/gin-gonic/gin/pull/2692#issuecomment-881370810 by @leafduo 
So I did these things below in this PR:
1. Update related documents.
2. Make `Engine.TrustedProxies` private, force people to use `Engine.SetTrustedProxies()` to set proxies.
3. Added proxies safety check and notices in `Run`, `RunTLS`, etc. 
4. Completed related unit tests.
**This PR should be published with** #2692 .

Tidy: Complete TrustedProxies feature

---

tree.go
tree_test.go

fix tsr with mixed static and wildcard paths

---

binding/default_validator.go
binding/default_validator_benchmark_test.go
binding/default_validator_test.go

This PR allows to cast error returned by ShouldBindWith functions when input parameter is a slice.

Export struct sliceValidateError to allow error casting

---

tree.go

Hi, I find that the conflict message for catch-all wildcard with existing path segment is not clear enough during my use of gin framework, i.e. it only suggests that there is a conflict, but gives no hint about where the conflict is.
This PR will give a more user-friendly error message when users are trying to add two conflict routes as bellow:
```go
r := New()
r.GET("/foo/bar", nil)
r.GET("/foo/*bar", nil)
```
Error message before:
```
catch-all conflicts with existing handle for the path segment root in path '/foo/*bar' 
```
Error message now: 
```
catch-all wildcard '*bar' in new path '/foo/*bar' conflicts with existing path segment 'bar' in existing prefix '/foo/bar'
```

prettify error message for catch-all conflict with existing path segment

---

context_test.go
gin_test.go
githubapi_test.go
logger_test.go
middleware_test.go
recovery_test.go
routergroup_test.go
routes_test.go
utils_test.go

There are many packages that need to testing gin router like as below:
https://github.com/gin-contrib/static/blob/0b63c38653d9941a7851807d76e2692655cf6fc7/static_test.go#L16-L21 
So we can expose the `performRequest` function.

test(route): expose performRequest func

---

.github/workflows/codeql.yml
go.mod

feat(CodeQL): Discover vulnerabilities across a codebase with CodeQL

---

gin.go
gin_test.go
go.mod
go.sum

Support both http/1.x and h2c over the same plain tcp port. 
It is common to make h2c communication on the server side environment. However,  the standard **net/http** library does not support this feature in box ([more detail](https://github.com/golang/go/issues/14141)). It would be a great convenient for gin to support it.
This patch is extracted from 	[William Chang's work](https://go-review.googlesource.com/c/net/+/112999).

support h2c with prior knowledge

---

README.md

For upload section in README, there is a example of how to upload file through CURL:
```shell
curl -X POST http://localhost:8080/upload \
-F "file=@/Users/appleboy/test.zip" \
-H "Content-Type: multipart/form-data"
```
Noted that name of upload form is **file**, but in the example code above, this name is **Filename**, which is confused:
```go
func main() {
// Set a lower memory limit for multipart forms (default is 32 MiB)
router.MaxMultipartMemory = 8 << 20  // 8 MiB
router.POST("/upload", func(c *gin.Context) {
// Single file
file, _ := c.FormFile("Filename")
log.Println(file.Filename)
// Upload the file to specific dst.
c.SaveUploadedFile(file, dst)
c.String(http.StatusOK, fmt.Sprintf("'%s' uploaded!", file.Filename))
})
router.Run(":8080")
}
```
**Filename** …

doc: change the form name of upload example code

---

context.go
context_test.go
utils.go
utils_test.go

attachment filename support utf8
```
Content-Disposition: attachment; filename="new_filename.go"
Content-Disposition: attachment; filename*=UTF-8''new%F0%9F%A7%A1_filename.go
```
`golang.org/x/exp/utf8string` need golang 1.18
https://datatracker.ietf.org/doc/html/rfc5987
https://stackoverflow.com/questions/93551/how-to-encode-the-filename-parameter-of-content-disposition-header-in-http
https://stackoverflow.com/questions/53069040/checking-a-string-contains-only-ascii-characters

feat attachment filename support utf8

---

README.md
routergroup.go
routergroup_test.go
routes_test.go

I was miising feature of Serving file form http.FileSystem
there has StaticFile,Static,StaticFS method, since go1.16 embed feature, I am not find how to get a file from embed fs. follow is my want
```
//go:embed mypic.png
var pic embed.FS
func main() {
r.StaticFileFS("/alias_pic.png", "mypic.png", http.FS(pic))
err := r.Run(":9000")
if err != nil {
panic(err)
}
}
```
Use cases:
- Serve file by alias  from `http.FileSystem`

feat: add StaticFileFS

---

context.go

I find a bug about  missing `sameSite` when do context.reset()
Here is the bad case example:
```
package main
import (
"bytes"
"fmt"
"net/http"
"net/http/httptest"
"net/url"
"strings"
)
type responseBodyWriter struct {
gin.ResponseWriter
body *bytes.Buffer //cache
}
func (r responseBodyWriter) Write(b []byte) (int, error) {
r.body.Write(b)
return r.ResponseWriter.Write(b)
}
func (r responseBodyWriter) WriteString(s string) (n int, err error) {
r.body.WriteString(s)
return r.ResponseWriter.WriteString(s)
}
// test gonic context
func main() {
e := gin.New()
// middleware
e.Use(func(c *gin.Context) {
w := &responseBodyWriter{body: &bytes.Buffer{}, ResponseWriter: c.Writer}
c.Writer = w
c.Next()
// body := w.body.String()
path := c.Request.URL.Path
header := …
```

Fix: missing `sameSite` when do context.reset()

---

context.go
context_test.go

feat(context): return GIN Context from Value method

---

mode.go
mode_test.go

related issue: https://github.com/gin-gonic/gin/issues/3134

feat: automatically SetMode to TestMode when run go test.

---

README.md
binding/binding.go
binding/binding_nomsgpack.go
binding/binding_test.go
binding/toml.go
binding/toml_test.go
context.go
context_test.go
go.mod
go.sum
render/render.go
render/toml.go

This PR aims to add a TOML binding to the gin framework

[GIN-001] - Add TOML bining for gin

---

CHANGELOG.md

fixed #3167 
Already updated in Tag description.

docs(changelog): add break changes section

---

context.go
context_test.go
gin.go

due to breaking change in https://github.com/gin-gonic/gin/issues/3166

feat(context): add ContextWithFallback feature flag (#3166)

---

context.go

Noticed a small tense error on the doc for the `ClientIP()` method while reading the docs.

Doc fix: Small fix on Context's ClientIP() method.

---

.github/workflows/gin.yml
README.md
debug.go
debug_test.go

switch min version of go to 1.15

---

.github/workflows/gin.yml
Makefile
README.md
go.mod
go.sum
internal/json/sonic.go

Introduce a new drop-in json enhancement: [sonic](https://github.com/bytedance/sonic).

feat: add sonic json support

---

.github/workflows/gin.yml
context.go
context_test.go
errors.go
errors_test.go
ginS/gins.go
logger_test.go
middleware_test.go
mode.go
path.go
recovery.go
routergroup.go

upgrade golangci-lint to fix the follow issue:
```
Running [/home/runner/golangci-lint-1.45.0-linux-amd64/golangci-lint run --out-format=github-actions --verbose] in [] ...
panic: load embedded ruleguard rules: rules/rules.go:13: can't load fmt
goroutine 1 [running]:
github.com/go-critic/go-critic/checkers.init.22()
github.com/go-critic/go-critic@v0.6.2/checkers/embedded_rules.go:46 +0x4b4
Error: golangci-lint exit with code 2
Ran golangci-lint in 10051ms
```
and fix the follow error to using `gofmt -s -w *.go`
```
Running [/home/runner/golangci-lint-1.48.0-linux-amd64/golangci-lint run --out-format=github-actions --verbose] in [] ...
Error: File is not `gofmt`-ed with `-s` (gofmt)
Error: File is not `gofmt`-ed with `-s` (gofmt)
Error: File is not `gofmt`-ed with `-s` (gofmt)
Error: …
```

chore: upgrade golangci-lint and fix golangci-lint error

---

.github/workflows/gin.yml

This PR adds explicit [permissions section](https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#permissions) to workflows. This is a security best practice because by default workflows run with [extended set of permissions](https://docs.github.com/en/actions/security-guides/automatic-token-authentication#permissions-for-the-github_token) (except from `on: pull_request` [from external forks](https://securitylab.github.com/research/github-actions-preventing-pwn-requests/)). By specifying any permission explicitly all others are set to none. By using the principle of least privilege the damage a compromised workflow can do (because of an [injection](https://securitylab.github.com/research/github-actions-untrusted-input/) or compromised third party tool or …

GitHub Workflows security hardening

---

routergroup.go

There were a number of spots referring to a variable named "handle" that should be "handlers".

Fix typos in RouterGroup method docs

---

.github/workflows/gin.yml
go.mod
go.sum

Fix the GO-2022-0969 and GO-2022-0288 vulnerabilities

---

binding/default_validator.go
context_test.go
errors.go
gin.go
response_writer.go
routergroup.go

No need to create variables to validate interfaces, consistent with other code styles, Interface checks: [go.dev/doc/effective_go#blank_implements](https://go.dev/doc/effective_go#blank_implements)

fix: modify interface check way

---

context_test.go
gin.go
test_helpers.go

This PR trying to fix the issue we met, which exact same with https://github.com/gin-gonic/gin/issues/2778
If you guys have better idea to fix this, just let me know.

fix(engine): missing route params for CreateTestContext (#2778)

---

binding/binding_test.go
binding/multipart_form_mapping_test.go
binding/protobuf.go
context.go
gin_integration_test.go
gin_test.go
recovery.go
routes_test.go

remove deprecated of package io/ioutil

---

context.go

If you don't want to motify the annotation. Maybe I can fix it in the tree.go (func Get or func ByName).
Please feel free to reach out with any questions.
Thank you very much.

docs(context): #3369 modify the annotation about Context.Param()

---

response_writer.go
response_writer_test.go

@manucorporat @thinkerou @appleboy 
Hello Dears.
It looks like the console logger HTTP response code is not equal to the client(browser) HTTP status code in the case we set the response status code twice or more by mistake or whatever.
It would make some problems when we want to monitor our network traffic because the status code which we have is not right.
Please consider the following code:
```go
router.GET("/", func(c *gin.Context) {
c.String(http.StatusOK, "Status OK")
c.String(http.StatusUnauthorized, "Status Unauthorized")
})
router.Run()
```
If we make an HTTP request by curl:
```curl
curl -v 127.0.0.1:8080
```
We'll get 200 status by curl, but the console logger prints 401, and its not true.
I fixed this problem by preventing rewriting the HTTP status code …

console logger HTTP status code bug fixed

---

context.go

Using defer to unlock  is more in line with go standards

update context.go Get/Set method use defer

---

binding/yaml.go
go.mod
go.sum
render/render_test.go
render/yaml.go

about https://github.com/go-yaml/yaml/issues/865
fixes https://github.com/gin-gonic/gin/issues/3451
fixes https://github.com/gin-gonic/gin/issues/3306
fixes https://github.com/gin-gonic/gin/issues/3362
fixes https://github.com/gin-gonic/gin/issues/2581

chore(yaml): upgrade dependency to v3 version

---

routes_test.go
tree.go

Also add test to validate fix.
fixes https://github.com/gin-gonic/gin/issues/3459

fix(router): tree bug where loop index is not decremented.

---

context.go
context_test.go

fix(context): panic on NegotiateFormat - index out of range

---

README.md

And the [Brigade](https://github.com/brigadecore/brigade) is an archived CNCF project now.

chore(docs): Remove the Brigade project, because the Gin is no longer used in the latest version

---

debug_test.go
githubapi_test.go
logger_test.go
recovery_test.go

To build strings more efficiently, use strings.Builder instead.

Replace bytes.Buffer with strings.Builder where appropriate

---

routergroup.go
routergroup_test.go

I added the Match method to the IRoutes interface and RouterGroup struct for supporting multiple HTTP methods with single functionality and handler.
For example, this is common to use both PUT and PATCH methods when developing RESTful APIs for updating models.
Without this method, we should repeat ourselves to handle this.
With the Match method our routing signature is like this:
```go
r.Match([]string{http.MethodPut, http.MethodPatch}, "/", func(c *gin.Context) {
c.String(http.StatusOK, "This handler will support both PUT and PATCH methods.")
})
```

chore(router): match method added to routergroup for multiple HTTP methods supporting

---

response_writer.go
response_writer_test.go

This PR implements the go1.20 `http.rwUnwrapper` interface on the private gin.responseWriter type:
```go
type rwUnwrapper interface {
Unwrap() ResponseWriter
}
```
This will allow code using go1.20 to use the http.ResponseController utility type added in go1.20.
```go
engine.GET("/path", func (c *gin.Context) {
controller := http.NewResponseController(c.Writer)
controller.SetWriteDeadline(time.Second)
// ...
}
```

chore(http): add support for go1.20 http.rwUnwrapper to gin.responseWriter

---

gin.go
routes_test.go

Hi, Team.
I added a `escape logic` to the header reflecting user input values for the following.
I'd appreciate it if you could review it.
Basically `X-Forwarded-Prefix` is not required for any purpose other than the `/` delimiter. However, unintended execution by crafted request.
`X-Forwarded-Prefix` has a potential problems. Although actively exploiting this flaw is unlikely, Need to prevents abuse in scenarios such as [cache poisoning](https://portswigger.net/web-security/web-cache-poisoning).
```go
package main
import (
"net/http"
)
func main() {
r.GET("/bug", func(c *gin.Context) {
c.JSON(http.StatusBadRequest, gin.H{"msg": "bug"})
})
r.Run()
}
```
```bash
$ curl -L --path-as-is -i "http://192.168.1.19:8080/bug/" -H "x-forwarded-prefix: …
```

Add escape logic for header

---

gin.go
routes_test.go

Hi, @appleboy, @thinkerou 
Excuse me, I again think about https://github.com/gin-gonic/gin/pull/3500
I'm sorry to bother you.
`.` delimiter & Repeated `/` delimiter was judged to need to be delete and merge,
So, I request PR again.

Fix #3500 Add escape logic for header

---

recovery.go

Use `bytes.ReplaceAll(name, centerDot, dot)` instead of `bytes.Replace(name, centerDot, dot, -1)`, which looks more concise

refactor: use bytes.ReplaceAll directly

---

go.mod
internal/bytesconv/bytesconv_1.19.go
internal/bytesconv/bytesconv_1.20.go

Go official is expected to provide unsafe.{SliceData, Slice, StringData, String} series methods in version 1.20 for conversion of strings and slices.
Reference: https://github.com/golang/go/issues/53003

Convert strings and slices using the officially recommended way

---

gin.go

The current message points to a link that no longer exists since the section moved from the README to docs/doc.md
This commit changes the message to link to the documentation on GitHub (seems like the best option as the docs are not hosted elsewhere afaik)

docs: changed documentation link for trusted proxies

---

.github/workflows/gin.yml
.golangci.yml
README.md
codecov.yml
fs.go
recovery.go

- Update golangci-lint version from `v1.48.0` to `v1.52.2`
- Remove Gitter notifications from GitHub Actions workflow
- Add gosec linter settings and include specific rules
- Exclude revive linter for test files
- Remove Gitter badge from README.md
- Delete codecov.yml file
- Change function parameter name in fs.go
- Remove unused parameter in defaultHandleRecovery function

chore: improve linting, testing, and GitHub Actions setup

---

.github/ISSUE_TEMPLATE.md

fix typos in ISSUE_TEMPLATE.md
Corrected the port number used in the curl example in GitHub's ISSUE_TEMPLATE.md. Since the source code starts the server on port 9000, it is appropriate to specify the same port 9000 in the curl command.

Fix typos in ISSUE_TEMPLATE.md

---

context.go
context_test.go

https://github.com/gin-gonic/gin/issues/3555

fix lack of escaping of filename in Content-Disposition

---

context.go
context_test.go

Fixes nil pointer dereference panic introduced here: https://github.com/gin-gonic/gin/pull/3172
Closes https://github.com/gin-gonic/gin/issues/3343
Closes https://github.com/gin-gonic/gin/issues/3581
Closes https://github.com/gin-gonic/gin/issues/3483
Closes https://github.com/gin-gonic/gin/issues/3178
`c.engine.ContextWithFallback` check panics in `Deadline()`, `Done()`, `Err()` and `Value()` when `c.engine` is `nil`.
---

fix Request.Context() checks

---

gin.go

I think this comment is redundant.
The code already sufficiently conveys the meaning of `// Update maxParams`.

Remove redundant comments

---

binding/form_mapping.go
binding/form_mapping_test.go

Fixes issue #3659.
The pointer support in url query params (using `[]*Struct` for binding query params) was previously available in Gin, but was removed in commit 0d50ce859 since there wasn't a test case for such a scenario, and so the case block was removed as a redundant one. This PR re-adds the pointer support along with relevant tests.
Thanks @claneo for reporting #3659 in detail with the code change suggestion, and thanks @vkd for the background and review of re-adding this support.

fix: Add pointer support for url query params (#3659)

---

.github/workflows/codeql.yml
.github/workflows/gin.yml
.github/workflows/goreleaser.yml

- Change the cron schedule from `'0 17 * * 5'` to `"0 17 * * 5"` in the file `.github/workflows/codeql.yml`
- Change the value of `language` from `['go']` to `["go"]` in the file `.github/workflows/codeql.yml`
- Change the value of `go-version` from `'^1.18'` to `"^1.18"` in the file `.github/workflows/gin.yml`
- Add `1.21` to the list of `go` versions and change the value of `test-tags` in the file `.github/workflows/gin.yml`
- Change the value of `if` condition from `matrix.go-version == '1.20.x'` to `matrix.go-version == '1.21.x'` in the file `.github/workflows/gin.yml`
- Change the value of `on` from `'*'` to `"*"` in the file `.github/workflows/goreleaser.yml`
- Change the name of the job from `name: Checkout` to `name: Checkout` in the file `.github/workflows/goreleaser.yml`
- …

chore(ci): update GitHub Actions configuration (add go1.21)

---

.github/workflows/gin.yml
.golangci.yml
go.sum
tree.go

- Update the version of a tool in the GitHub workflow from `v1.52.2` to `v1.55.2`
- fix cache error from setup-go https://github.com/actions/setup-go/issues/427

ci(lint): update tooling and workflows for consistency

---

gin.go
routes_test.go

Previous work:
* #2476 : the present PR resolves issues still present in this (getting old) PR: conflicts & spacing. Original author's contribution should have been kept by git.
* #2404 : should be closed
Closes #2397

fix(header): Allow header according to RFC 7231 (HTTP 405)

---

binding/default_validator.go
binding/validate_test.go

fix(binding): dereference pointer to struct when validating structs

---

.github/workflows/gin.yml
.github/workflows/goreleaser.yml

- Update the version of gin to v1.56.1 in the `.github/workflows/gin.yml` file
- Add go version 1.22 to the list of supported versions in the `.github/workflows/gin.yml` file

ci(testing): add go1.22 version

---

context.go

Using 'make' to initialize the map('cp.Keys') with a length of 'c.Keys'.  
Avoiding repeatedly assiging the 'params' to 'context'.
Below is my local test code:
context.go
```golang
func (c *Context) Copy() *Context {
cp := Context{
writermem: c.writermem,
Request:   c.Request,
Params:    c.Params,
engine:    c.engine,
}
cp.writermem.ResponseWriter = nil
cp.Writer = &cp.writermem
cp.index = abortIndex
cp.handlers = nil
cp.Keys = map[string]any{}
for k, v := range c.Keys {
cp.Keys[k] = v
}
paramCopy := make([]Param, len(cp.Params))
copy(paramCopy, cp.Params)
cp.Params = paramCopy
return &cp
}
func (c *Context) NewCopy() *Context {
cp := Context{
writermem: c.writermem,
Request:   c.Request,
engine:    c.engine,
}
cp.writermem.ResponseWriter = nil
cp.Writer = &cp.writermem
cp.index = …
```

chore(perf): Optimize the Copy method of the Context struct

---

binding/binding.go
binding/binding_nomsgpack.go
binding/binding_test.go
context_test.go
render/render_test.go
render/yaml.go

[RFC 9512](https://www.rfc-editor.org/rfc/rfc9512.html) deprecates `application/x-yaml` in favor of `application/yaml`. This PR changes that in Gin, with two commits:
1. accepts `application/yaml` for bindings
2. uses `application/yaml` when rendering
The second one may be considered as a breaking change, hence the separate commit.

chore(header): Add support for RFC 9512: application/yaml

---

auth.go
auth_test.go

Function BasicAuth is not suitable for proxy-server authentication, so I add a brand new function `BasicAuthForProxy` in auth.go and test it.

feat(auth): add proxy-server authentication

---

context.go

> // This mutex protects Keys map.
> 	mu sync.RWMutex
In `Copy` method `Context.Keys` should be protected by `Context.mu` to aviod DATA RACE

fix: protect Context.Keys map when call Copy method

---

context_test.go
gin.go
gin_test.go

**I would like to add an `OptionFunc` to facilitate Gin configuration.**
> Note: This adjustment supports downward compatibility.
**Before:**
```go
package main
import "github.com/gin-gonic/gin"
func main() {
r := gin.New()
r.GET("/ping", func(c *gin.Context) {
c.JSON(200, gin.H{
"message": "pong",
})
})
r.Run(":8002")
}
```
**But now:**
- New Engine
```go
package main
import "github.com/gin-gonic/gin"
func main() {
var fc = func(e *gin.Engine) {
e.GET("/ping", func(c *gin.Context) {
c.JSON(200, gin.H{
"message": "pong",
})
})
e.Use(gin.Recovery())
}
r := gin.New(fc)
r.Run(":8002")
}
```
- With Engine:
```go
package main
import "github.com/gin-gonic/gin"
func main() {
r := gin.New()
r.With(func(e *gin.Engine) {
e.GET("/ping", func(c *gin.Context) {
c.JSON(200, gin.H{
"message": "pong",
}) …
```

feat(engine): Added `OptionFunc` and `With`

---

context.go

chore(request): check reader if it's nil before reading

---

deprecated.go

I hope to achieve that the IDE can recognize deprecated methods and guide users with correct prompts.

docs(context): Added deprecation comments to BindWith

---

path_test.go

I found an official example, I see the official example for the number of CPU cores for comparison, so I made a reference to the official adjustment.
**References:**
- https://github.com/golang/go/blob/master/src/path/path_test.go#L82-L85
- https://github.com/golang/go/issues/5000
- https://codereview.appspot.com/7545043

test(path): Optimize unit test execution results

---

codecov.yml

```yml
coverage:
require_ci_to_pass: true # This indicates that the code coverage must meet the specified targets in order for the CI (Continuous Integration) process to pass.
status:
project:
default:
target: 99% # This sets the code coverage target for the project to 99%. It means that at least 99% of the code needs to be covered by tests.
threshold: 99% # This sets the code coverage threshold for the project to 99% If the code coverage falls below 99%, the CI will be marked as failed.
patch:
default:
target: 99% # This sets the code coverage target for patches to 99%. It means that at least 99% of the patch code needs to be covered by tests.
threshold: 95% # This sets the code coverage threshold for patches to 95%. If the code coverage of a patch falls below 95%, the CI will be marked …
```

build(codecov): Added a codecov configuration

---

binding/query.go
binding/query_test.go

#3235 Reference
Changes: 
- [#e837e1c](https://github.com/gin-gonic/gin/commit/e837e1cd1850559d91d921b712bc7b0c8f78cf7e) changed query mapping function
- [#c17e9f1](https://github.com/gin-gonic/gin/commit/c17e9f1a1554d4a32d44131cf6f949606814ffbe) tests

fix(uri): query binding bug

---

context.go
context_test.go
docs/doc.md

Resolves https://github.com/gin-gonic/gin/issues/3823
Based on this https://github.com/gin-gonic/gin/issues/3823 proposal, I code about shortcuts
Ran into an issue like https://github.com/gin-gonic/gin/issues/3862 during testing
I hope to get some help.
This is my first time submitting code in open source。

feat: ShouldBindBodyWith shortcut and change doc

---

context.go

Initialize the m map with a length of len(c.Params)

chore(optimize): the ShouldBindUri method of the Context struct

---

.goreleaser.yaml

- Update the build configuration to skip the build using a comment
- Change the `changelog` use from `git` to `github`
- Modify the regex patterns for `Features`, `Bug fixes`, and `Enhancements` titles in the changelog
- Add a new regex pattern for the `Refactor` title in the changelog
- Update the excluded items in the changelog to include `docs` and `CICD` with corrected quotes

ci(release): refactor changelog regex patterns and exclusions

---

binding/form_mapping.go
binding/form_mapping_test.go
docs/doc.md
gin_test.go

Add `binding.BindUnmarshaler` interface to support custom unmarshaling (from the suggestion in https://github.com/gin-gonic/gin/issues/2673)
This PR is inspired by the information provided on the following page: [labstack/echo/v4#BindUnmarshaler ](https://pkg.go.dev/github.com/labstack/echo/v4#BindUnmarshaler) and  [PR-3045](https://github.com/gin-gonic/gin/pull/3045).
As [ssoroka](https://github.com/ssoroka) (the author of [PR-3045](https://github.com/gin-gonic/gin/pull/3045)) mentioned:
> This is way off my radar (it's been 2 years and I've switched to huma). Feel free to take over the change and apply it in a new PR."
Therefore, I would like to open a new pull request to implement this feature. However, I have identified two potential issues with PR-3045:
1. PR-3045 also introduces …

feat(binding): Support custom BindUnmarshaler for binding.

---

gin.go

Update link [1] to [2] after PR #3449 was merged.
[1] https://pkg.go.dev/github.com/gin-gonic/gin#readme-don-t-trust-all-proxies
[2] https://github.com/gin-gonic/gin/blob/master/docs/doc.md#dont-trust-all-proxies
Closes #3938

docs(gin): update link to dont-trust-all-proxies section (#3938)

---

fs.go
fs_test.go
routergroup.go

I want to serve static assets from an `embed.FS` instance without directory listing. The `onlyFilesFS` wrapper is a perfect fit.
This PR exports `onlyFilesFS`, adds unit tests and documentation.
Usage example:
```go
//go:embed dist/*
var assets embed.FS
router.StaticFS("/assets/", gin.OnlyFilesFS{FileSystem: http.FS(assets)})
```

feat(fs): Export, test and document OnlyFilesFS

---

.github/workflows/gin.yml
README.md
debug.go
debug_test.go

- Update the minimum Go version requirement for Gin from `1.20` to `1.21` in both `debug.go` and `debug_test.go`
- Modify the warning message to reflect the new minimum Go version requirement in `debug.go`
- Adjust the test assertion to match the updated warning message in `debug_test.go`
since https://github.com/gin-gonic/gin/pull/3210 PR import [quic-go/quic-go](https://github.com/quic-go/quic-go) package which require go v1.21 above.

build: update Gin minimum Go version to 1.21

---

binding/binding.go
binding/binding_nomsgpack.go
binding/binding_test.go
binding/plain.go
context.go
context_test.go

https://github.com/gin-gonic/gin/pull/2037
```go
package main
import (
)
func main() {
router.POST("/", func(c *gin.Context) {
var s string
c.BindPlain(&s)
c.String(200, s)
})
router.Run()
}
// client
// curl -d "test string" 127.0.0.1:8080
// output
// test string
```

feat(binding): add BindPlain

---

README.md

I tried to make the README a little more readable and also replaced a moved link

docs(readme): fix language and moved link

---

binding/default_validator.go
binding/default_validator_benchmark_test.go

Enhance code readability by replacing the original "switch statement and if conditionals" with a simple "for loop" to iterate over the error slice.
Below is my local test code:
default_validator.go
```go
type SliceValidationError []error
// Error concatenates all error elements in SliceValidationError into a single string separated by \n.
func (err SliceValidationError) Error() string {
n := len(err)
switch n {
case 0:
return ""
default:
var b strings.Builder
if err[0] != nil {
fmt.Fprintf(&b, "[%d]: %s", 0, err[0].Error())
}
if n > 1 {
for i := 1; i < n; i++ {
if err[i] != nil {
b.WriteString("\n")
fmt.Fprintf(&b, "[%d]: %s", i, err[i].Error())
}
}
}
return b.String()
}
}
func (err SliceValidationError) NewError() string {
if len(err) == 0 {
return ""
}
var b strings.Builder
for i := 0; …
```

refactor(slice): simplify SliceValidationError Error method

---

context.go
context_test.go

fix(context): check handler is nil

---

context.go
context_test.go

Fix the judgment logic flaw in Negotiate fucntion
solve https://github.com/gin-gonic/gin/issues/3965

fix(context): YAML judgment logic in Negotiate

---

context.go
context_test.go

When using a test context (as returned by `gin.CreateTestContext(w)`) it is possible that not only the Request object is nil, but also the URL object may be nil.
Ran into this in the wild in unit tests. Stack trace:
```
1. --- FAIL: Test_ListOrgs (1.09s)
2. panic: runtime error: invalid memory address or nil pointer dereference [recovered]
3.     panic: runtime error: invalid memory address or nil pointer dereference
4. [signal SIGSEGV: segmentation violation code=0x1 addr=0x60 pc=0x6e51ce]
5.  
6. goroutine 124 [running]:
7. testing.tRunner.func1.2({0x206ad60, 0x3dd8c30})
8.     /opt/hostedtoolcache/go/1.22.2/x64/src/testing/testing.go:1631 +0x24a
9. testing.tRunner.func1()
10.     /opt/hostedtoolcache/go/1.22.2/x64/src/testing/testing.go:1634 +0x377
11. panic({0x206ad60?, 0x3dd8c30?}) …
```

fix(context): verify URL is Non-nil in initQueryCache()

---

binding/form_mapping.go
binding/form_mapping_test.go

Resolves #3970
```golang
package main
import (
"fmt"
"net/http"
"strings"
)
type CustomPath []string
func (b *CustomPath) UnmarshalParam(param string) error {
elems := strings.Split(param, "/")
n := len(elems)
if n < 2 {
return fmt.Errorf("invalid path: %s", param)
}
*b = elems
return nil
}
type PathRequest struct {
Paths CustomPath `form:"path"`
}
func main() {
g := gin.Default()
g.GET("", func(c *gin.Context) {
var request PathRequest
if err := c.ShouldBind(&request); err != nil {
c.String(http.StatusBadRequest, "request parse err: %v", err)
return
}
c.String(200, "Hello %s", request.Paths)
})
g.Run(":9000")
}
Calling this server with a string parameters path will get the expected slices.
Example: 
$ curl 'http://127.0.0.1:9000?path=hello/world' 
CustomPath: …
```

feat(form): add custom string slice for form tag unmarshal (#3970)

---

gin.go
gin_integration_test.go
tree.go
tree_test.go

Implement literal colon support using the approach described in #1432

feat(router): add literal colon support (#1432)

---

docs/doc.md

Fixed a typo in "Gin Quick Start".

docs: fix typo in Gin Quick Start

---

gin.go
gin_test.go

fix(gin): Do not panic when handling method not allowed on empty tree

---

.golangci.yml
binding/binding_msgpack_test.go
binding/binding_test.go
binding/form_mapping_test.go
binding/multipart_form_mapping_test.go
binding/validate_test.go
context_test.go
debug_test.go
errors_test.go
fs_test.go
gin_integration_test.go
gin_test.go
githubapi_test.go
logger_test.go
path_test.go
render/render_msgpack_test.go
render/render_test.go
response_writer_test.go
routes_test.go
utils_test.go

This PR enables and fixes [testifylint](https://github.com/Antonboom/testifylint) linter to use best practices concerning testify

ci(lint): enable testifylint linter

---

binding/form_mapping.go
binding/form_mapping_test.go
docs/doc.md

Enables the possibility of collecting array data from queries or form data by specifying the collection_format tag in structs.
Several people are waiting for this feature to be updated.
cc @Simon-Saaw
Related PR: https://github.com/gin-gonic/gin/pull/2750
Close https://github.com/gin-gonic/gin/pull/2750

feat(form): add array collection format in form binding

---

binding/form_mapping.go
binding/form_mapping_test.go

- Use provided default value in struct tags when binding a request input to struct for validation.
Fixes: How to apply default value if empty value provided by client during model binding? #4042, #13042df, #a41721a

fix: Set default value for form fields

---

docs/doc.md

I have identified a couple of issues with the current example code for route groups in the documentation. Below are the details of these issues and the proposed fix.
In the current example code, there is a risk of making a typo that can lead to unintended behavior:
```diff
func main() {
// Simple group: v1
v1 := router.Group("/v1")
{
v1.POST("/login", loginEndpoint)
v1.POST("/submit", submitEndpoint)
v1.POST("/read", readEndpoint)
}
// Simple group: v2
v2 := router.Group("/v2")
{
v2.POST("/login", loginEndpoint)
v2.POST("/submit", submitEndpoint)
-     v2.POST("/read", readEndpoint)
+     v1.POST("/read", readEndpoint)
}
router.Run(":8080")
}
```
In the code above, the intention is to add endpoints to the v2 group, but due to a typo, the endpoint might accidentally …

docs: fix route group example code

---

context.go
context_test.go

Thanks for such a nice open-source web framework, when I was using gin middleware today I found that the support for go native types when getting the data from gin. I put in a uint8 type, for example I put in a uint8 type, which when I get it doesn't provide a quick method but requires me to type it myself. I added some get methods of go native type, please review and merge to help more people, thank you very much
gin.Context new add methods: 
- GetInt8
- GetInt16
- GetInt32
- GetUint8
- GetUint16
- GetUint32
- GetFloat32
- GetIntSlice
- GetInt8Slice
- GetInt16Slice
- GetInt32Slice
- GetInt64Slice
- GetUintSlice
- GetUint8Slice
- GetUint16Slice
- GetUint32Slice
- GetUint64Slice
- GetFloat32Slice
- GetFloat64Slice

feat: gin.Context GetXxx added support for more go native types

---

binding/form_mapping.go
binding/form_mapping_test.go
docs/doc.md

---
This PR adds support for default values for the "multi" and "csv" collection_format binding types introduced in PR #3986. 
- To circumvent the issue of parsing commas or needing to use regex, I set semicolon as the delimiter for "multi" and "csv"
- By merging this PR, we can also close PR #2744 from 2021 that was adding the same functionality to an older version of Gin
closes #2744

feat(form): Support default values for collections in form binding

---

context_test.go

fix some function names in comment

docs(context): fix some function names in comment

---

context.go
context_test.go

- fix typo for c.ShouldBindBodyWithPlain comment
`ShouldBindBodyWithJSON is a shortcut for c.ShouldBindBodyWith(obj, binding.JSON).` -> `ShouldBindBodyWithPlain is a shortcut for c.ShouldBindBodyWith(obj, binding.Plain).`
- by the way, fix some test functions in context_test.go for passing golang-lint

fix: fix typo for c.ShouldBindBodyWithPlain comment

---

.github/workflows/gin.yml
tree.go
tree_test.go

fix(tree): Keep panic infos consistent when wildcard type build faild
When I run the demo1
```go
// demo1
func main() {
router.GET("/abc/bar", nil)
router.GET("/abc/x*z", nil)
router.Run("localhost:8080")
}
```
it got the panic:`panic: no / before catch-all in path '/abc/x*z'`
but when i run the demo2
```go
// demo2
func main() {
router.GET("/abc/bar", nil)
router.GET("/abc/b*r", nil)
router.Run("localhost:8080")
} 
```
it got the panic: `panic: runtime error: index out of range [-1]`
Although the end result is the same(panic), the different panic informations may cause some confusion.
So, add the `i < 0` condition to keep the panic infos same

fix(tree): Keep panic infos consistent when wildcard type build faild

---

context.go

This PR introduces a generic function, getTyped[T any], to simplify value retrieval in the Context struct. It replaces repetitive type assertions in the GetString and GetBool methods and adds comments to previously uncommented functions.
Benefits:
Reduces Code Duplication: Centralizes type assertions.
Enhances Readability: Simplifies method implementations and improves documentation.

refactor(context): simplify "GetType()" functions

---

context.go
context_test.go

if it needs to check if the handler is nil, tie c.index shall always ++.
add testing case for https://github.com/gin-gonic/gin/pull/4083 credit by @zjj 
* Test with no handlers: Verifies that calling Next() on a context with no handlers does not change the index property.
* Test with one handler: Checks that a single handler is executed, the index is updated correctly, and the handler sets a key-value pair in the context.
* Test with multiple handlers: Ensures that multiple handlers are executed in sequence, the index is updated correctly, and each handler can set key-value pairs in the context.
* Key existence and value check: Confirms that the keys set by the handlers exist in the context and have the expected values.
* Handler chaining: Validates that handlers can call Next() to pass …

chore(context): test context initialization and handler logic

---

.golangci.yml
binding/form_mapping_test.go
context_test.go
gin_test.go
githubapi_test.go
recovery_test.go
routes_test.go

This PR enables and fixes [perfsprint](https://github.com/catenacyber/perfsprint) linter to use faster alternatives of `fmt.Sprintf`

ci(lint): enable perfsprint linter

---

.golangci.yml
auth_test.go
benchmarks_test.go
binding/binding_msgpack_test.go
binding/binding_test.go
binding/multipart_form_mapping_test.go
context_test.go
debug_test.go
deprecated_test.go
gin_test.go
logger_test.go
middleware_test.go
recovery_test.go
render/render_test.go
routes_test.go
utils_test.go

This PR enables and fixes [usestdlibvars](https://github.com/sashamelentyev/usestdlibvars) linter that detect the possibility to use variables/constants from the Go standard library.

ci(lint): enable usestdlibvars linter

---

context.go
context_test.go

The SaveUploadedFile method previously set folder permissions to 0o750 by default when creating directories. A third parameter, ...fs.FileMode, has been added to allow customizable permissions. This update enables users to optionally set folder permissions when creating directories and files with the SaveUploadedFile method.
``` go
// example
func SaveFile(ctx *gin.Context) error {
file, err := ctx.FormFile("file")
if err != nil {
return err
}
var perm fs.FileMode = 0o755
return ctx.SaveUploadedFile(file, "/asset/file", perm)
}
```

refactor(context): (reupload) Added an optional permission parameter to the SaveUploadedFile method (#4068)

---

.github/workflows/gin.yml

- Add Go version `1.24` to the GitHub Actions workflow

ci: add go version 1.24 to GitHub Actions

---

.golangci.yml

https://github.com/gin-gonic/gin/actions/runs/13537431187/job/37831527911?pr=4167
`fiximports` property is not allowed under the `perfsprint`, move `fiximports` to `goimports` section.
`exportloopref` linter has been deprecated since Go1.22, replace `exportloopref` with `copyloopvar`.

fix: move fiximports to goimports section in golangci.yml

---

.github/workflows/gin.yml
.golangci.yml
README.md
debug.go
debug_test.go
go.mod
go.sum

- Update Go versions in workflow file to `1.23` and `1.24`
- Enhance test tags in workflow with specific linker flags
- Remove the conditional formatting step for Go `1.22.x` in workflow
- Remove `goimports` settings from `.golangci.yml`
- Update `go.mod` to use Go `1.23.0`
- Upgrade `github.com/bytedance/sonic` from `v1.11.6` to `v1.13.1`
- Update indirect dependencies `sonic/loader` to `v0.2.4` and `base64x` to `v0.1.5` in `go.mod`

chore: update Go versions and dependencies for improved compatibility

---

binding/binding_test.go
binding/form_mapping.go
docs/doc.md

This PR is copied from PR #3257 with minor changes. The original PR was never merged so I am raising this to actually merge the changes and add support for unixmilli and unixmicro time formats.
The original issue regarding this change is #2634 (which was closed for some reason even though no fix was ever merged)

feat(binding): add support for unixMilli and unixMicro (see #2634)

---

binding/toml.go

```go
// binding/toml.go:29
func decodeToml(r io.Reader, obj any) error {
decoder := toml.NewDecoder(r)
if err := decoder.Decode(obj); err != nil {
return err
}
return decoder.Decode(obj)
}
```
- Removed the redundant second call to `decoder.Decode(obj)` which caused incorrect behavior.
- Added a `validate(obj)` function to ensure proper validation of decoded TOML data.
- Fixes potential issues with data integrity caused by duplicate decoding.

fix(binding): prevent duplicate decoding and add validation in decodeToml

---

gin.go
gin_test.go

prevent middleware re-entry when handling context multiple times
Should fix https://github.com/gin-gonic/gin/pull/3641

fix: prevent middleware re-entry

---

docs/doc.md

This PR is editing the English grammar and spelling of several comments and instructions throughout the `docs/doc.md` file. 
While reading the [doc](https://github.com/boyczuk/gin/blob/master/docs/doc.md) for help with authentication I noticed that there are quite a few spots where the instructions had redundant or incorrect grammar. I scanned through and hopefully corrected all of the big ones.
**Before:**
```
Skip validate: when running the above example using the above the `curl` command, it returns error.
Because the example uses `binding:"required"` for `Password`.
If you use `binding:"-"` for `Password`, then it will not return error when running the above example again.
```
**After:**
```
Skip-validation: Running the example above using the `curl` command returns an error.
This is …
```

docs: Fixing English grammar mistakes and awkward sentence structure in doc/doc.md

---

binding/protobuf.go
ginS/gins.go

I used AI to find ​two spelling errors in words  😂
- "on error"  -> "an error"
- "util now" -> "until now"

docs: fix comment with AI

---

README.md

Fixes a broken link in the English README file that was pointing to an outdated documentation URL.

fix(readme): fix broken link to English documentation

---

render/json.go

This change improves code clarity by replacing the hardcoded ASCII boundary check (r >= 128) 
with the semantic constant unicode.MaxASCII, making the intention of the condition more explicit.

refactor: replace magic number 128 with unicode.MaxASCII in AsciiJSON render

---

.github/workflows/gin.yml
docs/doc.md
go.mod
go.sum
internal/json/json.go
internal/json/sonic.go

Closes #4233
- Drop `amd64` build constraint
- Drop redundant `avx` build tag

fix: sonic on arm64

---

errors.go
errors_test.go

fix(errors): change Unwrap method receiver to value type

---

internal/fs/fs_test.go

Fixes the test function name `TesFileSystem_Open`, which caused the **success** case for `FileSystem.Open` to be ignored during test runs.

test(internal/fs): fix test function name

---

recovery.go
tree.go

Replaced `strings.SplitN` with `strings.Cut` to reduce memory allocations and improve performance.   
`strings.Cut` also simplifies the code, making it more readable and maintainable.  
Below is my local test code.  
recovery_test.go
```go
package gin
import (
"strings"
"testing"
)
func headersStr(s string) string {
headers := strings.Split(s, "\r\n")
for idx, header := range headers {
current := strings.Split(header, ":")
if current[0] == "Authorization" {
headers[idx] = current[0] + ": *"
}
}
headersToStr := strings.Join(headers, "\r\n")
return headersToStr
}
func headersStrOptimized(s string) string {
headers := strings.Split(s, "\r\n")
for idx, header := range headers {
key, _, _ := strings.Cut(header, ":")
if key == "Authorization" {
headers[idx] = key + ": *"
}
}
headersToStr := …
```

perf(all): use strings.Cut to replace strings.SplitN

---

context.go
context_test.go
docs/doc.md

This PR adds a new `SetCookieStruct` method to the `Context` type that accepts a `*http.Cookie` pointer instead of individual parameters. This gives users more flexibility in setting cookie attributes, especially those not directly exposed by the current `SetCookie` method (such as `Expires`, `Partitioned`, etc).
The existing `SetCookie` method is preserved for backward compatibility.
- Added `SetCookieStruct` method to `context.go`
- Added corresponding test cases in `context_test.go`
- Updated documentation in `doc.md` to demonstrate usage
Resolves #4215

feat(context): add SetCookieData

---

context_test.go
middleware_test.go

fix some function names in comment

chore: fix some function names in comment

---

context_test.go

This PR fixes meaningless assertions in `context_test.go`.

fix(context): useless asserts

---

binding/form_mapping.go
binding/form_mapping_test.go

Fixes: #4098 
In `setTimeField`, when the string `val` is empty and the `timeFormat` is `unix` or `unixnano`, an error occurs due to `strconv.ParseInt` handling empty values. We can handle this by filling it with a zero value before parsing.

fix(time): binding time with empty value

---

binding/form_mapping.go
binding/form_mapping_test.go

Revert "fix(time): binding time with empty value"

---

context_test.go

After the unit tests are executed, clean up the test artifacts.

test(context): add cleanup for uploaded file in SaveUploadedFile test

---

recovery.go
recovery_test.go

Below is my local test code.  
recover/original.go
```go
package recover
import (
"bytes"
"fmt"
"os"
"runtime"
)
var (
dunno     = []byte("???")
centerDot = []byte("·")
dot       = []byte(".")
slash     = []byte("/")
)
// stack returns a nicely formatted stack frame, skipping skip frames.
func stack(skip int) []byte {
buf := new(bytes.Buffer) // the returned data
// As we loop, we open files and read them. These variables record the currently
// loaded file.
var lines [][]byte
var lastFile string
for i := skip; ; i++ { // Skip the expected number of frames
pc, file, line, ok := runtime.Caller(i)
if !ok {
break
}
// Print this much at least.  If we can't find the source, it won't show.
fmt.Fprintf(buf, "%s:%d (0x%x)\n", file, line, pc)
if file != lastFile {
data, err := os.ReadFile(file) …
```

perf(recover): replace bytes with strings in function for better performance

---

recovery.go
recovery_test.go

Hi :)
Extract Authorization header masking into maskAuthorization func for better readability.

refactor(recovery): extract Authorization header masking into maskAuthorization func

---

internal/bytesconv/bytesconv_test.go

This commit refactors random usage to follow current best practices in Go 1.20+:
- Replaced usage of `math/rand.Read`, which is deprecated, with `crypto/rand.Read`.
As per the deprecation notice, `crypto/rand.Read` is more appropriate for almost all use cases.
- Replaced `rand.NewSource(time.Now().UnixNano())` with `rand.New(rand.NewSource(time.Now().UnixNano()))`.
`rand.NewSource` returns a bare Source which lacks convenience methods like `Intn`, `Float64`, etc.
Wrapping it with `rand.New` provides a complete and idiomatic `*rand.Rand` object.

refactor(internal/bytesconv): replace rand usage with crypto/rand and rand.New

---

binding/yaml.go
go.mod
go.sum
render/render_test.go
render/yaml.go

This pull request replaces the YAML library `gopkg.in/yaml.v3` with `github.com/goccy/go-yaml` across the codebase to improve performance and functionality. It also updates the related dependency in `go.mod` and adjusts tests to account for differences in output formatting between the two libraries.
* [`binding/yaml.go`](diffhunk://#diff-de97edc270409bd81025ca51353a3d81975691edc4ca5724f39af9d3ab59bf76L12-R12): Replaced the import of `gopkg.in/yaml.v3` with `github.com/goccy/go-yaml`.
* [`render/yaml.go`](diffhunk://#diff-3063b5c3357edadb0e9efe88b86d7c73b5543d18491d8d76dfa41aafe2be29e5L10-R10): Updated the YAML library import to use `github.com/goccy/go-yaml` instead of `gopkg.in/yaml.v3`.
* [`go.mod`](diffhunk://#diff-33ef32bf6c23acb95f5902d7097b7a1d5128ca061167ec0716715b0b9eeaa5f6R10): …

chroe: migrate yaml package to github.com/goccy/go-yaml

---

debug.go

There is a mismatch between the Go version check logic and the warning message shown to users:
- Constant: `const ginSupportMinGoVer = 21`
- Message: `"[WARNING] Now Gin requires Go 1.23+\n"`
As a result, users running Go 1.21 or 1.22 cannot see the warning, even though the message states that 1.23+ is required.
The logic in `debugPrintWARNINGDefault()`:
```go
func debugPrintWARNINGDefault() {
if v, e := getMinVer(runtime.Version()); e == nil && v < ginSupportMinGoVer {
debugPrint(`[WARNING] Now Gin requires Go 1.23+.
`)
```
With ginSupportMinGoVer = 21, however, users on Go 1.21 (v = 21) or 1.22 (v = 22) don't trigger the warning (v < 21 is false).
Update the constant ginSupportMinGoVer to 23 to match the warning message indicating that Go 1.23+ is required.
This ensures users running Go …

Fixed version number discrepancy

---

mode.go

If `value` is null, it will be set to `test` or `debug` so it doesn't need to catch "" case anymore.

fix: remove impossible case

---

routergroup_test.go

```markdown
Add unit tests for `RouterGroup.combineHandlers` edge cases: handler limit validation and empty chain handling.
- **Handler Overflow**: Test panic when exceeding 63-handler limit
- **Empty Chains**: Test proper handling of empty handler slices
- Add `TestRouterGroupCombineHandlersTooManyHandlers` - validates panic on handler overflow
- Add `TestRouterGroupCombineHandlersEmptySliceNotNil` - ensures consistent empty chain behavior
```bash
go test -v -run TestRouterGroupCombineHandlers

test(route): add some test for routergroup

---

context.go
context_test.go

- The `get` method on `Context` did not use its receiver `c`, making it misleading.
- Renamed `get` to `getMapFromFormData` and made it a standalone function.

refactor(context): remove unused Context dependency in get method

---

response_writer.go
response_writer_test.go

The current implementation of the Hijack() method allows it to be called even after the response body has already been written to the client;
Go's internal implementation of http.Server is designed so that calling `Hijack ()` after `Write()` or `WriteHeader()` has been called is designed to return an error,
and the current Gin implementation differs from this.
Because of this difference,
some implementations of the underlying http.ResponseWriter may experience unexpected panics if Hijack() is called at an unintended time.
Therefore, we suggest changing the Hijack() method to check at the beginning of the method to see if the response has already been written
and return a clear and descriptive error if it has.
- Define an explicit error variable to return when `Hijack()` fails.
- At the …

Prevention of Hijack() runtime panics

---

context.go
context_test.go

```text
goos: darwin
goarch: amd64
pkg: github.com/gin-gonic/gin
cpu: Intel(R) Core(TM) i7-8569U CPU @ 2.80GHz
BenchmarkGetMapFromFormData
BenchmarkGetMapFromFormData/Small_Bracket
BenchmarkGetMapFromFormData/Small_Bracket-8         	 4073180	       299.7 ns/op	     336 B/op	       2 allocs/op
BenchmarkGetMapFromFormData/Small_Names
BenchmarkGetMapFromFormData/Small_Names-8           	 4073487	       272.4 ns/op	     336 B/op	       2 allocs/op
BenchmarkGetMapFromFormData/Medium_Bracket
BenchmarkGetMapFromFormData/Medium_Bracket-8        	 2672517	       448.2 ns/op	     336 B/op	       2 allocs/op
BenchmarkGetMapFromFormData/Medium_Names
BenchmarkGetMapFromFormData/Medium_Names-8          	 2494389	       463.8 ns/op	     336 B/op	       2 allocs/op …
```

perf(context): optimize getMapFromFormData performance

---

render/reader.go

Remove redundant headers parameter from Reader.writeHeaders method since it only passes r.Headers field.

refactor(render): remove headers parameter from writeHeader

---

.github/workflows/gin.yml

- Add a GitHub Actions job for vulnerability scanning using Trivy
- Configure Trivy to scan the repository for vulnerabilities of severity critical, high, and medium
- Ensure the workflow fails if vulnerabilities are found

ci: integrate Trivy vulnerability scanning into CI workflow

---

CHANGELOG.md
version.go

- Add release notes for Gin v1.11.0, detailing new features, enhancements, bug fixes, CI/build improvements, dependency updates, and documentation changes
- Update Gin framework version to v1.11.0
ref: https://github.com/gin-gonic/gin/issues/4325

docs(changelog): upgrade Gin to v1.11.0 and add release notes

---

README.md

- Add a new section announcing Gin 1.11.0 and link to its release blog post

docs: announce Gin 1.11.0 release with blog link

---

ginS/gins.go

Replacing sync.Once with sync.OnceValue can reduce 
the number of global variables and lines of code, 
and this approach is recommended in the Go source code.
https://go-review.googlesource.com/c/go/+/672235

refactor(ginS): use sync.OnceValue to simplify engine function

---

response_writer.go
response_writer_test.go

- Clarify the error message for attempted hijack after response body data is written
- Modify hijack behavior: allow hijacking after headers are written (for better websocket compatibility), but block hijacking after any body data is sent
- Add comprehensive tests to validate allowed hijack after header write and disallowed hijack after body write
fix https://github.com/gin-gonic/gin/issues/4372
Please ensure your pull request meets the following requirements:
Thank you for contributing!

fix(response): refine hijack behavior for response lifecycle

---

benchmarks_test.go

fix the incorrect function name in benchmarks_test.go

test(benchmarks): fix the incorrect function name

---

logger.go
logger_test.go

add colored latency to log output based on latency thresholds
This PR introduces a new function `LatencyColor` in the logger middleware of the Gin framework. This function assigns colors to log output based on the request latency, improving the readability and visual identification of performance bottlenecks.
The current logging system outputs latency as plain text, making it difficult to quickly identify performance issues at a glance. By adding color-coded latency information, developers can more easily distinguish between different latency levels, aiding in faster debugging and performance monitoring.
1. **Add LatencyColor Function**: Implement a function that returns a color string based on the request latency.

feat(logger):color latency
