examples/pluggable_renderer/example_pongo2.go
examples/pluggable_renderer/index.html

Gin meets pongo2!
(https://github.com/flosch/pongo2)

Add Pluggable View Renderer Example

---

gin.go

Fixd newline problem with debugPrint() in Run* functions

---

binding/binding.go

Fix unexported field detection

---

README.md

wrong spell

---

logger.go

colorful logger on windows

---

gin.go

I find that gin does not support listening socket, I add it.

support running with socket

---

errors.go

32 int overflows: https://github.com/gin-gonic/gin/issues/298

Patch for #298

---

logger_test.go

Not sure where the integration tests should go, ideally they would be run separately from unit tests.
=== RUN TestLogger
--- PASS: TestLogger (0.00s)
=== RUN TestColorForMethod
--- PASS: TestColorForMethod (0.00s)
=== RUN TestColorForStatus
--- PASS: TestColorForStatus (0.00s)

Added tests for colorForMethod() and colorForStatus()

---

gin_integration_test.go

im working on RunTLS() as well but its still WIP

add integration tests for Run() and RunUnix()

---

README.md
context.go
gin.go
middleware_test.go
routergroup.go

Minor rewrite of some documentation and code, related to issue #252.

Fix #252 typo (middlewares -> middleware)

---

README.md

I am looking for a long time , add this document will
help who were looking for graceful restart/stop like me.
Signed-off-by: ZhiFeng Hu <hufeng1987@gmail.com>

Add document about graceful restart or stop

---

gin.go

undefinitely -> indefinitely

---

logger_test.go

Possible wrong copy/paste TODO

Wrong copy/paste TODO

---

examples/app-engine/hello.go

Just run the following command
```
$ gofmt -w .
```
cc @manucorporat

fix: example format.

---

.travis.yml

@javierprovecho I added golang 1.5 and 1.6 version in `.travis.yml`.

Add 1.5 and 1.6 test.

---

gin_integration_test.go

This test sample is useful when gin user writes integration test.
Because httptest runs httpserver asyncrhronous and selects port number automatically if we want.

Add integration test using httptest

---

README.md

https://github.com/braintree/manners
cc @javierprovecho

Add manners package.

---

README.md

Fix #548 
Add upload file example code.
cc @javierprovecho

Add upload file example

---

README.md

I found some stuff in `README.md` that I thought could be improved on.

Fix typos and improve wording

---

README.md

ref https://github.com/gin-gonic/gin/commit/007bd5124afeeaa151bcbddc30d39ebd98e61f9a and https://github.com/gin-gonic/gin/issues/514

update readme: add YAML example.

---

README.md

Hi @javierprovecho 
I create the `example` section which include project lists using gin framework.

Add project lists using gin framework.

---

mode.go

I think assigning iota to each constant is not required

Removed additional Iota

---

.travis.yml
README.md

remove coveralls services.

---

errors.go

Details can be found in issue #630

Fix incorrect error implmentation

---

README.md

see the https://github.com/gin-gonic/gin/issues/742#issuecomment-264681292
cc @tboerger @javierprovecho 

Improve document for #742

---

README.md

Add comment for the logic behind func.

---

README.md
examples/upload-file/multiple/main.go
examples/upload-file/multiple/public/index.html
examples/upload-file/single/main.go
examples/upload-file/single/public/index.html

Add upload file example.

---

README.md

thanks @im7mortal
Fix multitemplate link

Fix #607 doc link

---

context.go
context_test.go

chore(errorHandler):new abortWithStatus method with Json body and contentType application/json

chore(errorHandler):new abortWithStatus method with Json body

---

.travis.yml
logger.go
vendor/vendor.json

feat: support cygwin for log writer.

---

context.go
context_test.go

feat: Support get value from request header.

---

context.go
context_test.go

fix https://github.com/gin-gonic/gin/issues/854
fix https://github.com/gin-gonic/gin/issues/438
fix https://github.com/gin-gonic/gin/issues/785

feat: add GetRawData func.

---

context_test.go

Improve cookie tests code coverage #871

Improve cookie tests code coverage

---

context_test.go

Add content negotiation tests code coverage #871

Add content negotiation tests code coverage

---

context.go
context_test.go

TODO:
(inspired by https://github.com/spf13/viper/blob/master/viper.go#L645)

feat(context): add cast helpers to c.Keys

---

context.go
context_test.go

Fix #928 Method to get main handler is desired

Add method to return main handler

---

vendor/vendor.json

fix https://github.com/gin-gonic/gin/issues/873

refactor: update protobuf version

---

path.go
path_test.go
tree.go
tree_test.go

Unify license to MIT license, but I am not sure, please review, thanks.

unify license

---

errors_test.go

Improve errors code coverage

---

.travis.yml
Makefile
binding/form_mapping.go
context.go
context_test.go
errors.go
gin_integration_test.go

* vet check
* fmt check
* embedmd check
* misspell check
fix #946 

Add Makefile to check the following thing

---

debug_test.go

https://github.com/gin-gonic/gin/pull/871

Improve debug code coverage

---

CONTRIBUTING.md

update document format.

---

README.md
examples/auto-tls/example2.go

https://github.com/gin-gonic/autotls/pull/1

fix: update autotls example.

---

examples/upload-file/multiple/main.go
examples/upload-file/single/main.go

fix https://github.com/gin-gonic/gin/issues/971

[example] add error check.

---

gin.go

This snippet have already passed by test coverage.

fix(comment): remove todo

---

routes_test.go

ref: https://codecov.io/gh/gin-gonic/gin/src/master/gin.go#L349

Improve serveError code coverage

---

render/html.go
render/json.go

Separate type define

---

README.md

docs(readme): add binding html checkbox example, close #129

---

vendor/vendor.json

chore(vendor): update jsonite rev, close #991

---

context_test.go
vendor/vendor.json

test failed, see https://github.com/json-iterator/go/issues/126
- [TestRenderIndentedJSON](https://github.com/gin-gonic/gin/blob/master/render/render_test.go#L55)

update json-iterator revison to fix TestRenderIndentedJSON failed

---

examples/http2/main.go

add warning using http2 example

---

vendor/vendor.json

refactor(render): upgrade json package.

---

vendor/vendor.json

chore(vendor): update jsonite rev, #1010

---

README.md

issue discovered by @sgon00 at gitter

docs(readme): fix single file example

---

vendor/vendor.json

according to https://github.com/gin-gonic/gin/pull/1026#issuecomment-315942327, update jsoniter vendor version.

chore(vendor): update jsoniter package.

---

auth.go
gin.go

remove invalid return

---

context.go

ref https://github.com/gin-gonic/gin/issues/1041#issuecomment-319125864 and https://github.com/gin-gonic/gin/issues/633

doc(context):  more clearer bind doc when input is not valid

---

routes_test.go

https://github.com/gin-gonic/gin/pull/1063#issuecomment-322041800 fix testing failed. Please review it thanks.

fix(test): only check Location header

---

logger.go

the screenshot of updated before:
the screenshot of updated after:

align log format

---

examples/app-engine/hello.go

Should use `net/http package` since it is imported from the UI perspective.

fix 200 to http.Status

---

README.md

fix https://github.com/gin-gonic/gin/issues/598#issuecomment-293086937

doc(readme): add additional middleware doc.

---

ginS/gins.go

not use dot when import package

---

auth.go
context.go

refactor: using requestHeader internal func.

---

ginS/gins.go

fix gins Undefined

---

context.go

doc(context): add cookie doc

---

binding/form.go

I think bit operations is not human readable in such usecases (compiler optimaze it anyway)

32 << 10 != 32 Mb

---

recovery.go

doc(recovery): add RecoveryWithWriter doc

---

auth.go
gin.go
mode.go
render/html.go
utils.go

The mothod is more readable because it's more obvious s is a string and not a slice.

Empty string check

---

README.md
examples/multiple-service/main.go

fix https://github.com/gin-gonic/gin/issues/346

feat: add multiple service example.

---

README.md

fix markdown render

---

debug.go

The constant is `ReleaseMode`, as defined in [mode.go](https://github.com/gin-gonic/gin/blob/1e88466d234a82ce4aeca904bce8a0b93fac3d42/mode.go#L16).

Update comment to reflect correct constant.

---

context_test.go
gin_test.go
logger_test.go
mode_test.go
path_test.go
recovery_test.go
routergroup_test.go
routes_test.go
utils_test.go

Hi, @appleboy I recommit the pull request for changing the param position of `assert.Equal`, thanks!

update assert param(expect, actual) position

---

render/render_test.go

Remove redundant if err != nil check

---

utils.go

Fix golint warnings in utils.go

---

gin.go

Fix some golint warnings in gin.go

---

README.md

Minor typo in README.md example code

---

binding/binding_test.go
binding/validate_test.go
render/render_test.go

assert.Equal(t, expected, actual)

unify assert.Equal usage

---

.travis.yml
README.md
examples/assets-in-binary/README.md
examples/assets-in-binary/assets.go
examples/assets-in-binary/html/bar.tmpl
examples/assets-in-binary/html/index.tmpl
examples/assets-in-binary/main.go
vendor/vendor.json

ref https://github.com/gin-gonic/gin/issues/1316#issuecomment-383348823

Add example to build single binary with templates

---

tree.go

Also fix the same typo in a comment

Fix typo in panic() message (extra single quote)

---

routergroup.go

server a single file -> serve a single file

minor typo in routergroup.go

---

README.md

doc: update readme for adding binding about skip validate

---

binding/binding.go
binding/default_validator.go

the pull request update `return error(err)` to `return err`, and remove `kindOfData`.

update error(err) to err

---

context.go
context_test.go

return json if jsonp has not callback

return json if jsonp has not callback

---

context.go
ginS/gins.go

Hello!
Looking through context package and found a little bit complicated switch block. And tried to make it easier.
Thanks!

Simplify context error

---

render/render.go

interface implement type check

interface implement type check

---

path.go

from httprouter patch: https://github.com/julienschmidt/httprouter/pull/243

small enhance for cleanPath

---

context_test.go
test_helpers.go

Attempt to fix #1462

---

render/render_test.go

improve render code coverage

---

.github/ISSUE_TEMPLATE.md
.github/PULL_REQUEST_TEMPLATE.md

ref: https://blog.github.com/2016-02-17-issue-and-pull-request-templates/
Hi, @javierprovecho @appleboy and everyone I commit two files about issue template and pull request template explain, I not setup them template but explain, ant the explain from `CONTRIBUTING.md`. Thanks!

add issue/pr template explain

---

vendor/vendor.json

upgrade lib version, and upgrade `github.com/json-iterator/go` to add two libs.

chore: upgrade dependency library version

---

render/msgpack.go

please see msgpack usage: https://github.com/ugorji/go/tree/master/codec#usage

render: update msgpack usage

---

render/reader.go
render/text.go

chore: add missing copyright and update if/else

---

binding/form_mapping.go
context.go
render/json.go

As[ Effective Go](https://golang.org/doc/effective_go.html?#if) about `if` said, remove else statement instead of return/continue statement.

chore: remove else instead of return/continue

---

README.md

format readme code import

---

.github/ISSUE_TEMPLATE.md

chore: update issue_implate

---

tree_test.go

Found using https://go-critic.github.io/overview#commentedOutCode-ref

remove debug print statements from test code

---

README.md
debug.go

Let's user define how he wants to log his routes (eg. JSON, key value, or something else)

---

.travis.yml

as title. docs: https://docs.travis-ci.com/user/customizing-the-build/#rows-that-are-allowed-to-fail

chore: recover go master build, partial revert #1514

---

.travis.yml

ref: https://blog.travis-ci.com/2013-11-27-fast-finishing-builds

ci: fast finish when build failed

---

debug_test.go

chore: fix debug test error

---

.travis.yml

remove allow fail flag from travis

---

README.md

fix wrong word

---

auth_test.go
context_17_test.go
context_test.go
render/render_test.go
routes_test.go

This pr contains a replacement of deprecated language feature

replace deprecated HeaderMap with Header()

---

Makefile

as title. Just update the golint to new URL.

fix(Makefile): golint to new URL

---

README.md

Add a new example (Set and get a cookie) to README.md.

Add example to set and get cookies

---

README.md

Missing the right colon

---

README_ZH.md

修复了全角括号导致超链接不能正常访问的错误。
修复了一些URL中的"/"被改成" / "的错误。
修复了一些包引用中"/"被改成" / "的错误。
修复有超链接被翻译成中文的错误。

修改连接错误，修正一些报引用错误

---

README.md

have agreed with project's author.
cc @alombarte
thanks!

add krakend to gin user list

---

README.md

agreed with the project's author.
cc @thoas
thanks!

add picfit to gin user list

---

tools/tools.go

chore: attemp to fix #1700

---

context_test.go

chore(testing): case sensitive for query string

---

routergroup.go

Fix case of GitHub

---

logger_test.go

Removing duplicate test

---

README.md

Fix Readme (Japanese text hiragana -> kanji)

---

examples/README.md

Doc: fix gin example notice syntax

---

README.md

#1844 #1838 
Keep the documentation in readme until full available on the new website.

chore(readme): rollback readme

---

ginS/gins.go

Fix spelling.

---

README.md

the condition in readme is wrong, use time.After is ok ;)

fix README.md example code bug

---

context.go

delete duplicate code, and keep in line with `GetQueryMap`

refactor(context.go): GetPostFormMap

---

tree.go

Make countParams more readable

---

mode_test.go

add TestDisableBindValidation

---

response_writer_test.go

Change Writter to Writer.

---

tree.go

from: https://github.com/julienschmidt/httprouter/commit/b9a36063a10f224c4ae2596f12964d9e59443515#diff-37cf0fd7a164303538a2d22d965646df

tree: sync httprouter update

---

README.md

Excuse me, I forgot change output in #2186

Update to currently output

---

README.md

Passed my manual test, output nothing different.

Update validator to v10

---

README.md

Remove broken link from README.

---

path.go
tree.go

copy from https://github.com/julienschmidt/httprouter/commit/15782a78c61201cf2fdbc138d63aa60fff114695

docs(path): improve comments

---

tree.go

copy from https://github.com/julienschmidt/httprouter/commit/cfa3cb764b4fc4eb98cae67a2020a91c79e065be

tree: remove duplicate assignment

---

context.go
context_test.go

Implement YAML support for negotiation (see #2157)

add yaml negotitation

---

CHANGELOG.md

docs: Add 1.6 changelogs

---

version.go

bump to v1.6.1 version

---

CHANGELOG.md
version.go

Release v1.6.3 version

---

BENCHMARKS.md
README.md

As title. Gin v1.6.3 benchmark result.

docs: update benchmark result v1.6.3

---

README.md

uncomment the code in README

---

BENCHMARKS.md

 Broken link repo typo fix

---

debug_test.go

New test case added  for custom format using DebugPrintRouteFunc()

DebugPrintRouteFunc() unit test

---

README.md

https://github.com/gin-gonic/examples/pull/39

Docs: Update README.md Custom Validator sample code

---

CHANGELOG.md
binding/form_mapping_test.go
context_test.go

Fix spelling

---

README.md

Signed-off-by: Zasda Yusuf Mikail <zasdaym@gmail.com>

Add some missing dots on README

---

.travis.yml
README.md

ci: romove go1.11 for gin1.7

---

context.go

Minor fixes on comments. No additional test is needed.

Fix typos in context.go

---

internal/bytesconv/bytesconv.go

Remove the tedious named return value

---

CHANGELOG.md
version.go

bump to v1.7.0 version

---

.travis.yml
CHANGELOG.md
version.go

bump to v1.7.1

---

CHANGELOG.md
version.go

chore(docs): bump to v1.7.2

---

context.go

optimize code

---

go.mod
go.sum

Upgrade github.com/ugorji/go/codec

---

binding/default_validator.go

The default validator has upgraded from v8 to v10, but its docs link didn't.

Update default validator's docs link

---

tree.go
tree_test.go

Fix insufficient slice check

---

gin.go

byte alignment

---

routergroup.go

use assert1 func

---

CHANGELOG.md
version.go

fixed https://github.com/gin-gonic/gin/issues/2799

docs: release v1.7.3

---

.github/workflows/gin.yml

In 1.42.0 revive bump from 1.0.9 to 1.1.0

bump golangci-lint

---

binding/form_mapping.go
binding/multipart_form_mapping.go
errors_test.go

There’s no such word as `setted`, `set` is set, set, setting

setted typo fix

---

context.go

fix: description error

---

README.md

don't-trust-all-proxies --> dont-trust-all-proxies

FIX hash link typo at README.md

---

README.md

docs: redirect to the correct line of code

---

README.md

Distinguish between group and nested group

---

routes_test.go

@appleboy please review the pr firstly, thanks!

fix: test error

---

tree.go

Annotation fix

---

auth.go

use StringToBytes func

---

.github/workflows/goreleaser.yml
.goreleaser.yaml
version.go

chore(CI/CD): add go version release flow

---

AUTHORS.md
CHANGELOG.md
binding/toml.go
binding/uri.go
render/render_msgpack_test.go

@appleboy please review, thanks!
and update Authors.md

add v1.8.0 changelog

---

CHANGELOG.md
version.go

docs: release v1.8.1 version

---

README.md

docs: update markdown format

---

routergroup.go

FIX TYPO: Gin by default useR -> ... useS

---

binding/binding_test.go
binding/form_mapping_test.go
render/render_test.go

refactor(struct): Remove redundant type conversions

---

CHANGELOG.md
README.md

docs(comment): Modify comment syntax error

---

gin_test.go

fix: test fmt.Println replace t.Error

---

context.go

fix: fix typo in comment

---

README.md

docs(readme): Modify sample code bugs

---

CHANGELOG.md
version.go

See the milestone: https://github.com/gin-gonic/gin/milestone/23
@thinkerou Please help to review and comments if missing another PR.

docs(readme): release v1.8.2 version

---

binding/toml.go

this is more like a code formatting job，adjust the function decodeToml in file `binding/toml.go` to same formatting of `binding/yaml.go` and `binding/msgpack.go` which decodeXXX fund is in tail
Forgive my poor English

Adjust the position of some functions

---

.github/workflows/goreleaser.yml

chore(CI): update release args

---

go.mod

Patches https://security.snyk.io/vuln/SNYK-GOLANG-GOLANGORGXNETHTML-5816820

Upgrade golang.org/x/net -> v0.13.0

---

logger.go
logger_test.go

Use white color for HTTP 1XX

---

context_test.go
docs/doc.md
gin.go

Also add some more detail to the docs for how to use TrustedPlatform.
https://fly.io/docs/reference/runtime-environment/#fly-client-ip

chore(IP): add TrustedPlatform constant for Fly.io.

---

render/render.go

Interface checks: [go.dev/doc/effective_go#blank_implements](https://go.dev/doc/effective_go#blank_implements)

chore(refactor): modify interface check way

---

.gitignore

test(git): gitignore add develop tools

---

context.go

docs: fix typo in function documentation

---

context_test.go

fix: https://github.com/gin-gonic/gin/actions/runs/8234650896/job/22517007644#step:5:176

fix(engine): fix unit test

---

auth.go

Add document comments to function `BasicAuthForProxy`

---

auth.go

docs: Add document  to constant `AuthProxyUserKey` and  `BasicAuthForProxy`.

---

binding/binding.go

support override default binding implement

feat(binding): support override default binding implement

---

Makefile

ci(Makefile): vet command add .PHONY

---

.goreleaser.yaml

- Add new changelog categories for "Build process updates" and "Documentation updates"

ci(changelog): update categories and improve documentation

---

.goreleaser.yaml

- Remove filters from the `changelog` section in `.goreleaser.yaml`

ci: refactor configuration files for better readability

---

version.go

- Update the version constant from "v1.9.1" to "v1.10.0"

docs: update version constant to v1.10.0

---

gin.go

Solved: https://github.com/gin-gonic/gin/pull/3572#pullrequestreview-2042946463

docs(engine): fix comments for the `With`

---

go.mod

fix(go): invalid Go toolchain version

---

Makefile

- Added `help` to Makefile.
- Provided brief descriptions for existing targets.

ci(Makefile): added help and descriptions to targets

---

tree.go

replace the self-defined 'min' to official one and solve the func 'max' name conflict in tree.go.

chore(tree): replace the self-defined 'min' to official one 

---

README.md

docs(readme): replace godoc with pkg

---

docs/doc.md

Hi!
I found some continuous whitespaces, so trimmed some.
Would appreciate if you take a look, thank you!

docs: trimmed some white spaces

---

CHANGELOG.md
context.go

docs: fix case error of X-Real-IP

---

gin_test.go

test(lint): fix lint failures

---

README.md

add gin-gonic/contrib in README

docs(readme): add gin-gonic/contrib

---

gin.go

This PR fixes a small typo and adds a comma for clarity in comments

docs: small changes

---

docs/doc.md

fix(docs): missing go markdown codeblock

---

context.go
context_test.go

Added function `AbortWithStatusPureJSON` for return `PureJSON`

feat: added `AbortWithStatusPureJSON()` in `Context`

---

doc.go

I thought it could be further improved by adding simple usage examples so that new users can quickly understand how to use GoDoc and the source code when they see it directly.
This change will make package documentation more helpful and convenient for developers new to the Gin framework.

docs: added comment in doc.go

---

binding/form_mapping.go
logger.go

This PR fixes grammatical errors in code comments by correcting improper article usage. The changes improve the overall quality and professionalism of the codebase documentation.
- **Before**: `// SkipPaths is an url path array which logs are not written.`
- **After**: `// SkipPaths is a URL path array which logs are not written.`
- **Reason**: "URL" is pronounced with a consonant sound (/juː/), so it should use the article "a" instead of "an". Also standardized "url" to "URL" for consistency.
- **Before**: `// UnmarshalParam decodes and assigns a value from an form or query param.`
- **After**: `// UnmarshalParam decodes and assigns a value from a form or query param.`
- **Reason**: "form" starts with a consonant sound, so it should use the article "a" instead of "an".
- **No functional …

fix: correct article usage in comments

---

render/toml.go

fixed https://github.com/gin-gonic/gin/issues/4320

chore(render): do not export tomlContentType anymore

---

.github/workflows/gin.yml
README.md
context_test.go
debug.go
debug_test.go

- Update minimum required Go version from 1.23 to 1.24 throughout documentation, warnings, and tests
- Remove Go 1.23 from the GitHub Actions workflow matrix
- Change single quotes to double quotes for consistency in workflow configuration
Please ensure your pull request meets the following requirements:
Thank you for contributing!

chore(go): bump minimum Go version to 1.24 and update workflows
